### ISSUE TITLE
`turbo run --help` inconsistency

### ISSUE THREAD

**Issue by Wyatt-Stanke** [vercel/turbo#1081]
### What version of Turborepo are you using?

1.2.4

### What package manager are you using / does the bug impact?

npm, pnpm, Yarn v1, Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Mac

### Describe the Bug

`turbo run --help` shows:
```
Usage: turbo run <task> [options] [-- <args passed to tasks>]

    Run tasks across projects in your monorepo.
...
```
The thing is that `turbo run` runs a pipeline, not tasks.

### Expected Behavior

I think it could print something like:
```
Usage: turbo run <pipeline> [options] [-- <args passed to tasks>]

    Run tasks across projects in your monorepo through pipelines.
...
```

### To Reproduce

- Run `turbo run --help`

**Comment by mehulkar** [comment]
Hey @Wyatt-Stanke sorry this issue has been open for so long. Seems your suggestion is about using the word `pipeline`? I think we want to stick to `task` as the thing you run. A pipeline is a set of tasks (which is really kind of an internal implementation detail in turbo about how it constructs the graph of tasks). I know `turbo.json` has a top level configuration called "pipeline", but IMO, it should always have been called `tasks`, because the user isn't designing the pipeline manually, they are declaring a set of tasks and their dependencies. _Turbo_ figures out the pipeline. 

Anyway, this reply is a year and a half later, so I'm going to close this down. Thank you for making the effort to file an issue about this!
