### ISSUE TITLE
Updating a dependency is not invalidating other application's cache

### ISSUE THREAD

**Issue by mcrowder65** [vercel/turbo#1084]
### What version of Turborepo are you using?

1.2.4

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

When updating a shared library, it's not invalidating the cache of projects that depend on that library.

I am updating a component called Button.js, and when running the build scripts, the projects that depend on the shared library's Button.js are replaying the cached output rather than running build again.

### Expected Behavior

When updating Button.js inside of the shared library, it should invalidate the project's cache that depends on shared.

### To Reproduce

Repository: https://github.com/mcrowder65/turbo-bug
Run:

```bash
yarn
yarn build
```

Update shared/src/button.js to something else.

`yarn build`

Note that the cache is invalidated, and it rebuilds the all projects.

Now if you checkout the branch called `broken`

Update shared/src/button.js to something else.

`yarn build`

Note that the cache is NOT invalidated, and it replays the previous build

A workaround for this with 1.2.4 is to add `"shared/**/*"` to `"globalDependencies"` inside of `turbo.json`

**Comment by sppatel** [comment]
I am seeing the same issue.

**Comment by sppatel** [comment]
@jaredpalmer I think this is a high severity blocking issue.  We have a large mono repo with both public and private packages.  The public packages have dependencies on private packages.  If a private package changes, only it is getting build, but at noted above, all its consumers replay cached builds.   

I don't think the workaround is a scalable solution.  Is there any way to get this prioritized soon?

**Comment by sppatel** [comment]
Actually the workaround does not work as their are a large set of packages i would need to add to the global cache - turbo can't handle it..

```
 git hash-object exited with status: fork/exec /usr/local/bin/git: argument list too long
 ```

**Comment by sppatel** [comment]
Ok, I was playing around with the example repo - seeing what works and what doesn't.  It looks like the key thing is having your build depend on ^build.

Also if you are using filters in CI against origin/main for example you'll need to filter with `filter=...[origin/main]` such that when it does an incremental build it also builds consumers.

**Comment by mcrowder65** [comment]
The build should depend on ^build? 🤔

**Comment by sppatel** [comment]
> The build should depend on ^build? 🤔

Yes - exactly.  The documentation does not make that obvious - and only indicates the usage of ^ to be soley for ensuring dependencies get built first.  But playing around with the example repo, it also appears to be critical to add to get this scenario working.  

I'll defer to the turbo repo folks on whether this is the intended behavior and correct solution - but i think this is a better solution then setting it as a global dependency.  Try it out - would be curious and good to confirm if it works for you with this change.

**Comment by mcrowder65** [comment]
I tried it last night and it was indeed the fix for this repo. Will report back on Monday if it fixes my work repo.

**Comment by mcrowder65** [comment]
@sppatel Tried this this morning, doesn't work for me because my shared library does not run the build command, because it all gets compiled into the projects when they get built themselves. 😢

**Comment by sppatel** [comment]
> @sppatel Tried this this morning, doesn't work for me because my shared library does not run the build command, because it all gets compiled into the projects when they get built themselves. 😢

Hmm.. Thats exactly how the example repo works, there is no build command for the shared projects.  Without the ^build dependency, you'll get cached results.

**Comment by avaragado** [comment]
I'm seeing a similar issue - with linting, in this case. This is with npm 8.5.3.

I have a monorepo with workspaces under `apps`, `libs`, and `tools` directories. Each workspace's name is npm-scoped with the relevant directory name. Workspaces under `tools` relate to infrastructure, such as linting configuration. So workspaces under `libs`, eg `@libs/beacons`, have devDependencies on `@tools/eslint`, `@tools/tsconfig`, and so on.

In `turbo.json`:

```json
    "lint:code": {
      "dependsOn": [],
      "outputs": []
    },
```

And here's what happens when I change the eslint configuration between linting runs:

```
❯ npm run lint:code -- --filter=@libs/beacons

> monorepo@0.0.0 lint:code
> cross-env FORCE_COLOR=1 turbo run lint:code "--filter=@libs/beacons"

• Packages in scope: @libs/beacons
• Running lint:code in 1 packages
@libs/beacons:lint:code: cache miss, executing e8f8367e4e3173f1
@libs/beacons:lint:code:
@libs/beacons:lint:code: > @libs/beacons@0.0.0 lint:code
@libs/beacons:lint:code: > eslint . --fix || true
@libs/beacons:lint:code:

 Tasks:    1 successful, 1 total
Cached:    0 cached, 1 total
  Time:    8.257s


~/monorepo
❯ echo '// asdf' >> tools/eslint/index.js

~/monorepo
❯ npm run lint:code -- --filter=@libs/beacons

> monorepo@0.0.0 lint:code
> cross-env FORCE_COLOR=1 turbo run lint:code "--filter=@libs/beacons"

• Packages in scope: @libs/beacons
• Running lint:code in 1 packages
@libs/beacons:lint:code: cache hit, replaying output e8f8367e4e3173f1
@libs/beacons:lint:code:
@libs/beacons:lint:code: > @libs/beacons@0.0.0 lint:code
@libs/beacons:lint:code: > eslint . --fix || true
@libs/beacons:lint:code:

 Tasks:    1 successful, 1 total
Cached:    1 cached, 1 total
  Time:    100ms >>> FULL TURBO
```

As `@libs/beacons` dev-depends on `@tools/eslint`, I would expect that changing `@tools/eslint` would invalidate any cached output from `@libs/beacons`. From the above transcript, it isn't.

I can make turbo.json look like this:

```json
    "lint:code": {
      "dependsOn": ["^lint:code"],
      "outputs": []
    },
```

Which does correctly invalidate the cache when I change `@tools/eslint`. But `^lint:code` causes all the other internal dependencies of `@libs/beacons` that have a `lint:code` task to run that task: in my case, 5 other workspaces. This just clutters up the output and burns some CPU pointlessly.

**Comment by cinan** [comment]
The `^build` had confused me too. My understanding of `^build` task is that all dependencies must complete task `build` first -- and that's it. In fact, it seems it has also another extremely important effect -- it computes task hash from dependencies files too. I'm not saying it's wrong, just confusing.

**Comment by avaragado** [comment]
That does seem to be the reality, yes. And I'd argue that it's wrong as well as confusing.

See https://turborepo.org/docs/core-concepts/caching#hashing - particularly the bullet "The hashes of all internal dependencies". I may be wrong, but I interpret that to mean "The hashes of all workspaces in the monorepo that the package depends on". If I'm wrong, I'd like to know what it actually means.

**Comment by sppatel** [comment]
Totally agree this is confusion and some clarification is needed.   @avaragado and yes, the ^lint:code depends on triggers unnecessary tasks just to get the consuming package to fire its task.

So I just found a reasonable workaround to this problem such that the correct package will get built/lint/etc.. WITHOUT having the downstream packages having to fire as well.

1.  Create a "fake" task in turbo with empty inputs and outputs.

```
 "fake": {
      "inputs": [],
      "outputs": []
    },
```
Now, instead of..

```
"lint:code": {
      "dependsOn": ["^lint:code"],
      "outputs": []
    },
```

Have your task depend on ^fake.

```
"lint:code": {
      "dependsOn": ["^fake"],
      "outputs": []
    },
```

Follow a similar approach to other tasks that need this behavior.

**Comment by mehulkar** [comment]
When inputs are not specified, turbo should take the input file list from package topological dependencies as well. That would solve this issue.

currently only the workspace’s files are considered inputs.

**Comment by jordyvanraalte** [comment]
In VS-code, I needed to rebuild the package and reset the cache (by reloading the developer window) to see my dependency updates in the other packages.

**Comment by nathanhammond** [comment]
Hey everybody; I'm going to close and lock this. The canonical discussion on a path forward is over at #2855.

With one small tweak (construction of the dep graph), the strategy proposed by @sppatel (thanks!) is the correct approach:

```
{
  "pipeline": {
    "fake": {
      "dependsOn": ["^fake"]
    },
    "lint:code": {
      "dependsOn": ["fake"]
    }    
  }
}
```

In short: this behavior is intentional. We're exploring alternative ways to make it easier to be successful with it, but it's not a bug. Over the last year we have _significantly_ improved our documentation story around this as well: https://turbo.build/repo/docs/core-concepts/monorepos/task-dependencies#dependencies-outside-of-a-task
