### ISSUE TITLE
Unable to run command when package#task defined `turbo.json` is missing

### ISSUE THREAD

**Issue by weyert** [vercel/turbo#1161]
### What version of Turborepo are you using?

1.26.0

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

If you have _manually_ 'pruned' your monorepo so that it only includes the packages that are used by the target project and try to run a command such as `turbo run build` then it can fail when the `turbo.json` file defined a task, such as:

```json
    "webapp#build": {
      "outputs": [".next/**", "dist/**", "public/dist/**"],
      "dependsOn": ["webapp#prebuild", "^build"]
    }
```

The `webapp`-package is not included in the _pruned_ mono repo the `turbo` command fails with an error like:

```bash
Error preparing engine: found reference to unknown package: webapp in task webapp#prebuild
```

### Expected Behavior

Able to execute commands which don't depend on missing packages

### To Reproduce

Working on this

**Comment by solaldunckel** [comment]
Any progress on this issue ?

**Comment by joshmedeski** [comment]
I'm also dealing with this issue. We created a pruned workspace but Turbo build command fails because it's detecting an app in the `turbo.json` that has been pruned out.

Our current fix is a duplicate `turbo.json` file that has manually removed those pruned pipelines. This is a poor solution as we have to keep multiple `turbo.json` files up-to-date.

Hopefully, the prune command can auto-generate an appropriate `turbo.json` file that fits the pruned workspace.

**Comment by gsoltis** [comment]
`turbo prune` is undergoing a bunch of work right now, I'll make sure that we get to this as part of the overhaul.

**Comment by mjrobinson86** [comment]
Also having this problem with yarn as a package manager, a workaround of multiple turbo.json files works but as pointed out, not ideal. Have to say though very impressed with turborepo overall as a tool, clever stuff :)

**Comment by vstreame** [comment]
I ran into this today. For those that don't want to wait for a fix, this script worked for me: https://gist.github.com/vstreame/b9b51ebc00af912f1e591da3a2e9bce3

The way how I use it in my `Dockerfile`s:

It's a drop in replacement for the `turbo run` command in my Dockerfiles. I just COPY this script into the container and call _it_ instead of `turbo run`.  Note, it requires `bash` and `jq` be available on the container.

**Comment by sladg** [comment]
Hey! Just a note into what I found. My packages are named as `@project/package-name` in their respective `package.json`s. I thought that Turbo is using folder name (aka `packages/package-name`), however that is not the case and I got it working by using name inside `package.json`. Hope it helps someone 🙃

**Comment by acauquil** [comment]
Pruning is THE feature that made me move to turborepo.
Pretty sad that I can't actually use it without hacking 😢
