### ISSUE TITLE
Additional arguments are passed to dependecies

### ISSUE THREAD

**Issue by majidsajadi** [vercel/turbo#1744]
### What version of Turborepo are you using?

1.4.3

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

this is my `turbo.json`

```json
{
  "$schema": "https://turborepo.org/schema.json",
  "pipeline": {
    "build": {
      "dependsOn": ["^build"],
      "outputs": ["dist/**"]
    },
    "app#build": {
      "dependsOn": [
        "^build",
        "$VITE_APP_NAME",
      ],
      "outputs": ["dist/**"]
    },

  },
  "globalDependencies": [".env.*"]
}
```

and this is my `package.json`

```json
{
  "workspaces": [
    "packages/*",
    "apps/*"
  ],
  "scripts": {
    "build": "turbo run build",
    "build:app": "turbo run build --filter=app"
  },
}
```

when i run `yarn build:app -- -- --mode development` the `-- --mode development` is passed to the app build script and all dependencies build script.

### Expected Behavior

according to this in the document

Note that these additional arguments will not be passed to any additional tasks that are run due to dependencies from the [pipeline](https://turborepo.org/docs/reference/configuration#pipeline) configuration.

i expect the add additional arguments will not be passed to dependencies tasks

### To Reproduce

`turbo.json`:
```json
{
  "$schema": "https://turborepo.org/schema.json",
  "pipeline": {
    "build": {
      "dependsOn": ["^build"],
      "outputs": ["dist/**"]
    },
    "app#build": {
      "dependsOn": [
        "^build",
        "$VITE_APP_NAME",
      ],
      "outputs": ["dist/**"]
    },

  },
  "globalDependencies": [".env.*"]
}
```

`package.json`:
```json
{
  "workspaces": [
    "packages/*",
    "apps/*"
  ],
  "scripts": {
    "build": "turbo run build",
    "build:app": "turbo run build --filter=app"
  },
}
```

```bash
yarn run build:app -- -- --mode dev
```

in the log you can see mode is passed to packages too.

**Comment by chris-olszewski** [comment]
The docs are out of date as we do pass these arguments. We're working on a better way to configure args on a per dependency basis, but haven't settled on a good way to express this in `turbo.json`.

**Comment by majidsajadi** [comment]
so is there any solution or workaround? this problem literally blocks me from deploying my project to different environments.
or should I wait for the new version?

**Comment by RMcNeely** [comment]
I actually found this post b/c I was looking to see if there's a way to contribute to the docs for Turborepo  in order to better explain that options are passed to all tasks including to dependencies but I guess that's a bug? Either way it is super unclear, I woudln't mind contributing some docs updates if thats something the project is open too (it could reference this bug if that's acceptable).

We had this pop up where we were passing the `--production` flag to Webpack in the `build` pipeline but that unfortunately caused our other packages using SWC to crash. I resolved this issue by adjusting the scripts in the workspaces and the pipelines. Now I have a `deploy` pipeline that calls a `build:prod` where I pass the flag to Webpack. The `deploy` task has a dependency on the non prod tasks that invoke `build` in our packages with SWC. Definitely not an ideal solution but a good work around.

**Comment by curlykay9527** [comment]
Has there been any progress on this issue? 
I have encountered the same problem and hope that the turbo additional arguments can be passed on without being transmitted to the dependencies.

**Comment by miccoh1994** [comment]
For others who may find this and have a similar context to me, I am running a monorepo in which I pass --base vite option to apps for building, I use plain tsc to compile some of my dependencies, which complains about the unrecognized passed arguments. I just swopped out tsc for tsx in those packages and tsx does not seem to care.

**Comment by anthonyshew** [comment]
Looks like this issue is addressed in today's documentation: https://turbo.build/repo/docs/reference/command-line-reference/run

**Comment by hchangjae** [comment]
I solved.

```json
...
"build": "tsc # prevent additional parameter"
...
```
