### ISSUE TITLE
Include the dependencies on how a hash is computed into verbose logs

### ISSUE THREAD

**Issue by iduuck** [vercel/turbo#2099]
### Describe the feature you'd like to request

I am currently trying to find out, why my turbo repo is constantly missing the cache, and tried the `-vvv` flag, but this isn't giving me any meaningful insights on why the cache is being missed.

It would be awesome to get an overview, of what is being used to compute the cache hash, so that I could see what the config is missing/has too much.

### Describe the solution you'd like

See above, solution is described above.

### Describe alternatives you've considered

No alternatives right now.

**Comment by thekip** [comment]
I have the same problem, it would be nice to see what exactly bursting the cache. 
I tried to integrate Trubo instead of our current task runner https://github.com/folke/ultra-runner which is doing mostly the same (incremental builds, deps graph and etc). But that constant cache bursting stopping me. 

By the way ultra-runner is awesome and shows what exactly bursting the cache, but miss some important features from turbo (cache in one folder vs spread across monorepo, prune command)

**Comment by mehulkar** [comment]
Just wanted to say that I'm going to be starting work on this soon! Stay tuned

**Comment by mehulkar** [comment]
Hey @iduuck and @thekip , try out the `--summarize` flag in any `turbo run`. Documentation coming in https://github.com/vercel/turbo/pull/4467. (Please file new issues if there are more things you want!)
