### ISSUE TITLE
Document best practices for sharing static assets across apps / packages

### ISSUE THREAD

**Issue by sbuys** [vercel/turbo#2192]
### Describe the feature you'd like to request

It is not clear what the recommended best practices are for sharing static assets across apps.

Current examples show duplication of shared assets - e.g. favicon is duplicated in the public folder across multiple next apps. What is the ideal structure for a monorepo with: shared images, font files, etc.

### Describe the solution you'd like

Documentation should include recommended best practices for packaging shared assets:

- How should users structure their monorepo?
- How to handle special file types?

### Describe alternatives you've considered

- Manually copy shared assets via script to public folder of each app
- Create package containing static files that can be imported by apps (but running into some issues with CSS imports and file URLs pointing to package)

**Comment by MildTomato** [comment]
One idea I had was creating a next.js site in the monorepo, and serve it locally at some port number like localhost:3004.
and then we'd have a env var in all our apps like, NEXT_PUBLIC_ASSETS_URL set to localhost:3004, and then prepend all our image urls with that.

Obviously for prod/staging/previews etc you would replace the env var with whatever the domain is.

This sort of worked, but then it doesn't work for vercel previews, since your assets site will always get deployed on a different preview url :(

---

other ideas i had was having some script in the mono repo that could 'duplicate' all the assets into each app, but that's also quite confusing for anyone just coming across our monorepo and wanting to contribute.. feels like we would be making things more confusing then,

**Comment by Walidoux** [comment]
any updates?

**Comment by algoflows** [comment]
any updates?

**Comment by tomerlichtash** [comment]
public static updates as any?

**Comment by lvilasboas-dti** [comment]
any updates?

**Comment by anthonyshew** [comment]
As an open-source etiquette reminder, note that comments like "+1" and "any updates?" hinder the ability of maintainers to deliver the best project possible. If you'd like to share your interest in a feature, please use the reaction feature on the original post.

---
As far as I know, sharing static assets isn't something that we're able to solve with Turborepo easily without building a standalone feature. Because of how JavaScript/TypeScript monorepos work, this would be a net-new accomplishment (again, as far as I'm aware).

As such, I'll close this as it isn't a documentation gap but a feature request. If you'd like to make a feature request for this, you can open a new issue!
