### ISSUE TITLE
turbo prune fails - Failed to encode pruned lockfile

### ISSUE THREAD

**Issue by blewisCycle** [vercel/turbo#2313]
### What version of Turborepo are you using?

1.6.1

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Mac

### Describe the Bug

When running
`turbo prune --scope=<app>`
I get an error that says:
`“Failed to encode pruned lockfile: Unable to find entry for react-dom@npm:16.14.0”`
All versions of React-DOM within the repo are set to 18.2.0.
Sometimes it will say “unable to find entry for react@npm:16.x.x”, but all versions of react are also version 18.2.0

### Expected Behavior

prune executes successfully

### To Reproduce

Run yarn dlx turbo prune --scope=signup at repo root directory
Fails every time.
```
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 0s 456ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed
➤ YN0000: ┌ Link step
➤ YN0007: │ turbo@npm:1.6.1 must be built because it never has been before or the last one failed
➤ YN0000: └ Completed in 0s 340ms
➤ YN0000: Done in 0s 808ms
Generating pruned monorepo for signup in /Users/brycelewis/Documents/working-folder/cycle-web-monorepo/out
 - Added signup
 - Added cycle-openapi
 - Added core
 - Added tsconfig
 - Added eslint-config-custom
 - Added ui
 - Added tailwindcss-config
 ERROR  Failed to encode pruned lockfile: Unable to find entry for react-dom@npm:16.14.0
```

**Comment by chris-olszewski** [comment]
Is there anyway you can provide the original lockfile you're trying to prune?

**Comment by blewisCycle** [comment]
Of course:

**Comment by blewisCycle** [comment]
/Users/brycelewis/Documents/working-folder/cycle-web-monorepo/.yarnrc.yml

/Users/brycelewis/Documents/working-folder/cycle-web-monorepo/yarn.lock

**Comment by blewisCycle** [comment]
Of course:

[yarn.lock.txt](https://github.com/vercel/turbo/files/9890289/yarn.lock.txt)
[.yarnrc.yml.txt](https://github.com/vercel/turbo/files/9890291/default.yarnrc.yml.txt)

**Comment by chris-olszewski** [comment]
I'm pretty stumped on this one since at the time of parsing the lockfile there's no references to `react-dom@npm:16.14.0`. It seems like the lockfile is getting extended while pruning somehow, but unsure how that could happen.

If you could share a reproduction with me that would help a lot. Also might as well try upgrading to `1.6.2` as it includes #2269 which I don't think relates to this issue, but is worth a shot.

**Comment by jsbrain** [comment]
I'm facing a similar problem.

In my case, the error is:

```txt
Failed to encode pruned lockfile: Unable to find entry for antd@npm:4.21.7
```

It happens with my react app which is built with [refine](https://github.com/refinedev/refine) and [refine-antd](@pankod/refine-antd).

While the latter one uses [antd](https://www.npmjs.com/package/antd) and re-exports it I'm actually not installing `antd` directly.

So without me installing `antd` everything works just fine, no problems whatsoever when building and running the app. But when I try to run `turbo prune --scope="web" --docker` I get the error.

Adding `"antd": "4.21.7"` to my package.json dependencies fixes the problem. But not this requires me to keep this entry in sync with the version `refine-antd` requires. Which is fine I guess but I would expect this is something I should not have to care for and should be detected automatically. I might be wrong though and this is the actual way to do it?!

I'm really not very good with all the dependency/peerDependency stuff but I would think this should not be of my concern as long as I don't use `antd` in another version anywhere else, which I don't.

**Comment by jsbrain** [comment]
To reproduce: https://github.com/jsbrain/turbo-prune-test

**Comment by jsbrain** [comment]
Also I should mention that this appears to be a `yarn 2+` problem. Using `yarn classic` actually works without issues.

**Comment by chris-olszewski** [comment]
@jsbrain Thank you so much for the reproduction, this helps me a lot!

**Comment by nathanhammond** [comment]
Hey everybody, I'm going to close _and lock_ this issue so that we are able to successfully distinguish between root causes with the same symptom. If you encounter something that looks like this, _please open a new issue_ with a _new reproduction_!

This also goes for anybody already contributing to this issue! @blewisCycle if after the next release if this doesn't end up addressing your issue please let us know by filing a new issue, and we will continue investigation there.

Thank you all for your help!
