### ISSUE TITLE
[turborepo] Explicit workspace-task to workspace-task dependencies do not respect --parallel flag

### ISSUE THREAD

**Issue by jdoltar** [vercel/turbo#3631]
### What version of Turborepo are you using?

1.7.2

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

Dependencies that are defined using the `<workspace>#<task>` syntax do not respect the `--parallel` flag.

Usecase: My monorepo is a collection of micro-frontends, they don't depend on each other at build time, they only depend on each other at runtime. Since they don't depend on each other at build time, they should all build in parallel. When running the dev server, however, turborepo should start serving any dependent micro-frontends automatically.

Given this relationship:
```json
{
  "pipeline": {
    "package-a#dev":  {
      "dependsOn": ["package-b#dev", "package-c#dev"]
    }
  }
}
```
When I run this:
```
turbo run dev --filter package-a... --parallel
```
It should run `package-a`, `package-b` and `package-c` in parallel.

### Expected Behavior

I would expect turborepo to execute the tasks in parallel. Instead, it waits for `package-b` and `package-c` to finish first before starting on the task for `package-a`. Since these tasks never end, `package-a` never starts.

### To Reproduce

Given `package-a`, `package-b`, `package-c`, and `package-d`. When `package-a` is running, I want  `package-b` and `package-c` to be running as well.

`turbo.json`
```json
{
  "$schema": "https://turborepo.org/schema.json",
  "pipeline": {
    "build": {
      "dependsOn": ["^build"],
      "cache": false
    },
    "dev":  {
      "cache": false
    },
    "package-a#dev":  {
      "dependsOn": ["package-b#dev", "package-c#dev"],
      "cache": false
    }
  }
}

```

`package.json`
```json
{
  "name": "turborepo-reproduce",
  "workspaces": [
    "packages/*"
  ],
  "scripts": {
    "build": "turbo run build",
    "dev": "turbo run dev --parallel",
    "dev-package-a": "turbo run dev --filter package-a... --parallel"
  },
  "devDependencies": {
    "turbo": "^1.7.2"
  }
}

```

> The `dev` task is meant to simulate running a local web server, it never finishes running unless user exits.

Reproduction steps using my [reproduction repo](https://github.com/jdoltar/turborepo-reproduce)

1. `yarn install`
2. `yarn build`
3. Observe build tasks running in parallel
4. `yarn dev`
5. Observe dev tasks running in parallel.
6. `yarn dev-package-a`
7. Observe relevant dev tasks NOT running in parallel (they should be)

I am forced to define the relationship using the `devDependencies` like so: [turborepo-reproduce/compare/main...workaround](https://github.com/jdoltar/turborepo-reproduce/compare/main...workaround)
 This is not ideal because then the build tasks will depend on each other as well. I could execute with the `--parallel` flag but that wouldn't work if there were actual build-time dependencies in the mix.

### Reproduction Repo

https://github.com/jdoltar/turborepo-reproduce

**Comment by mehulkar** [comment]
The effect of `--parallel` is to [remove the edges in the Workspace Graph][1] we build. But it looks when we build the _task_ graph, this [only affects topographical dependencies][2]. Dependencies declared with `workspace#task` syntax or even `task` syntax are still considered blocking. I'm not sure if this is intentional or not. 

Can you speak more to why you're configuring these dev tasks to depend on each other if you want to run them with `--parallel` anyway? Can you remove the relationship? We also have a [`persistent:true`][3] configuration you can add to tasks that don't exit to find cases where you may have accidentally created this relationship, if that helps.

[1]: https://github.com/vercel/turbo/blob/d66abefa5dfb82b03cdfbe206ed47a170b7de0be/cli/internal/run/run.go#L300-L305
[2]: https://github.com/vercel/turbo/blob/d66abefa5dfb82b03cdfbe206ed47a170b7de0be/cli/internal/core/engine.go#L287-L288
[3]: https://turbo.build/repo/docs/reference/configuration#persistent

**Comment by jdoltar** [comment]
@mehulkar I have a collection of micro-frontends, some of them pull in various modules from other micro-frontends via webpack's module federation. These micro-frontends do not depend on each other at build time, they only depend on each other at run time – they are essentially peer dependencies.

Is there another way to achieve what i'm after here? It would be cool if I could define these relationships with the `peerDependencies` section in the package.json and then have turbo repo always run peer dependencies in parallel. This could be a cool feature, but I think I would still prefer to define this relationship in the turbo.json as I have above.

**Comment by mehulkar** [comment]
> they only depend on each other at run time – they are essentially peer dependencies.

It seems turbo's definition of "dependsOn" may be different from yours. `dependsOn` defines the _order_ in which to execute tasks. For two long running servers, the order probably _doesn't_ matter. I don't have direct experience with micro-frontends or Webpack's module federation, but what happens if you remove the `dependsOn` relationship? `turbo run dev --parallel` will still run all three servers in parallel, so any dependencies through webpack should still work as you expect. As far as I can tell, I don't think the turbo config is buying you anything here, but I could be misunderstanding something!

**Comment by productdevbook** [comment]
same problem As soon as the filter is applied, this structure is completely broken. , Also, it doesn't do intelligent sorting like dev, and therefore the packages that need to be built get builds lately or in the middle, or the dev goes through.

**Comment by anthonyshew** [comment]
Going to close since the behavior described is exactly how `--parallel` is meant to work.
