### ISSUE TITLE
[turborepo] turbo-ignore seems to conflict with Vercel's "Promote to production"

### ISSUE THREAD

**Issue by lkostrowski** [vercel/turbo#3773]
### What version of Turborepo are you using?

1.7.4

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

"Promote to production" feature in Vercel is being cancelled by `turbo-ignore`, when promoting deployment 

### Expected Behavior

"Promote to production" in Vercel should work, because `NEXT_PUBLIC_VERCEL_ENV`, so turbo cache should be different

### To Reproduce

1. Deploy one of packages in https://github.com/saleor/apps. Set "production" branch to some new branch that is not important 
2. Add env variable "preview" specific to "main" branch and another for "production".
3. Add `npx turbo-ignore` to ignore build step
4. Push something to main
5. Try to "promote to production"

Build gets cancelled

### Reproduction Repo

https://github.com/saleor/apps

**Comment by anthonyshew** [comment]
We now encourage the use of our [new feature to automatically ignore unchanged deployments](https://vercel.com/changelog/automatically-skip-unnecessary-deployments-in-monorepos). While this bug may or may not be resolved since the original report, it should address the same use case in a much better way.
