### ISSUE TITLE
I can't read yellow on a white background

### ISSUE THREAD

**Issue by jtlapp** [vercel/turbo#3799]
### What version of Turborepo are you using?

1.7.4

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

I am unable to read yellow text on a white background. Here's an example, but mind you, readability will depend in part on your monitor.

![Screen Shot 2023-02-14 at 08 20 49](https://user-images.githubusercontent.com/138133/218751345-b256f062-ab29-48af-9469-b12ef49139fb.png)

Copying and pasting to an editor reveals the text: "No tasks were executed as part of this run."

### Expected Behavior

I should be able read Turborepo output.

### To Reproduce

Add a task to `turbo.json` that doesn't correspond to any `package.json` scripts, and run this task.

**Comment by mehulkar** [comment]
The Warning color is hardcoded to Yellow here:
https://github.com/vercel/turbo/blob/74f9f6eebc1c5d8323643313280f6d0d3fbcecbd/cli/internal/ui/ui.go#L118

I'm not sure of standard practice here for color contrast, since the background of your terminal could be any color. Maybe we could revisit this and take the background into account somehow.

**Comment by jtlapp** [comment]
It ought to at least be presentable and white and black. Any other color is non-standard, buyer beware.

I'm not fond of the colored text anyway. I've commented on another open issue about having once been left typing black text on a black background, making it invisible. I had to close the terminal window.
