### ISSUE TITLE
[turborepo] Regression: turbo run --filter[branch] throws an unexpected error

### ISSUE THREAD

**Issue by notaphplover** [vercel/turbo#3896]
### What version of Turborepo are you using?

1.8.1

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

`turbo run --filter[branch]` seems to throw an error when no tasks have to be run. I just published [this repository](https://github.com/notaphplover/turborepo-issue) with a minimal example to reproduce the bug.

### Expected Behavior

I expect turbo to not to fail to detect my pipeline tasks. Turbo version `1.7.4` is working as expected as you can see in https://github.com/notaphplover/turborepo-issue/tree/fix/behavior

### To Reproduce

Everything is detailed in [this repository](https://github.com/notaphplover/turborepo-issue).

### Reproduction Repo

https://github.com/notaphplover/turborepo-issue

**Comment by mehulkar** [comment]
@notaphplover thanks for the report and for the reproduction --that helped me narrow down the issue very quickly! You're right this is a regression, I'll try to get a patch out ASAP. 

Roughly speaking, the issue is that `--filter` reduces the list of affected packages. In 1.8 we made the part about looking up task definitions lazy (in order to support [Workspace Configurations](https://turbo.build/repo/docs/core-concepts/monorepos/configuring-workspaces)). Since there are no packages to look through, instead of exiting successfully with a no-op, turbo isn't able to find the task `foo` in the affected packages list.

**Comment by tknickman** [comment]
Fix should now be available in 1.8.2 @notaphplover!

**Comment by notaphplover** [comment]
> Fix should now be available in 1.8.2 @notaphplover!

Thank you so much! That was incredibly fast
