### ISSUE TITLE
[turborepo] Allow selecting cache hash saving strategy - before or after tasks execution

### ISSUE THREAD

**Issue by b12k** [vercel/turbo#3969]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

Hello,

It would be great to be able to choose cache hash saving strategy for a specific task.

Right now, according to the docs, cache hash is calculated BEFORE task execution. It makes some issues related to tasks which modify files.

For example releasing a package, when `npm version` bumps respective field in package.json.

Currently it makes cache miss on every run. OR using a custom hack - cache hit happens on second run.

If it will be possible to store cache hash AFTER an execution it will work as expected.

PS: this doesn't exclude initial cache hash calculation to determine whether task should be executed or "replayed". 

Similar to https://github.com/vercel/turbo/issues/3948

### Describe the solution you'd like

```json
{
  "$schema": "https://turborepo.org/schema.json",
  "pipeline": {
    "release": {
      "dependsOn": ["^release"],
      "outputMode": "new-only",
      "cacheStrategy": "after" // "before" as a default
    }
  }
}
```

### Describe alternatives you've considered

Creating a custom hack - script which skips execution of the task if there is no commits affecting the workspace.

**Comment by nathanhammond** [comment]
We're investigating something like this! We've been calling it `dynamicHash`. We're working on the design internal to the team, the constraints on when and how to run tasks that are dynamic while still being able to get as much performance out of the system as possible is tricky. We very much appreciate your feedback because your stated interest in this feature helps us prioritize our backlog.

If you know of additional needs you want to ensure get covered you can leave your thoughts here, but as we're tracking this elsewhere I am going to close the issue.

Thank you so much!
