### ISSUE TITLE
Allow turbo prune --docker without scope

### ISSUE THREAD

**Issue by ArnaudRinquin** [vercel/turbo#4074]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

At the moment (turbo 1.8.3), the `prune` command requires a `--scope=<target>` [argument.](https://turbo.build/repo/docs/reference/command-line-reference#turbo-prune---scopetarget). 

While it totally makes sense in normal context, it would be super useful for it to be optional when `--docker` is passed. 

This would provide an easy way to split the `yarn install` step from the other build tasks, as advised in example, but without focusing on any specific package.

```
FROM base-image AS pruner
RUN yarn global add turbo
COPY . .
RUN turbo prune  --docker # no --scope !

FROM base-image AS builder
COPY --from=pruner /slite/out/json/ . # like in example
RUN yarn install

COPY --from=pruner /slite/out/full/ . # like in example
RUN yarn turbo build # no focus either
```

In our case it we are considering lint, building etc... the whole repo in one image build without specific focus. And build other images picking from this base builder image.

### Describe the solution you'd like

Ideally, when no scope is passed along --docker, turbo should just copy all workspaces packages.json files, yarn.lock etc... and inputs files like usual, only this could be optimized as there's no need to slim down yarn.lock or anything.

### Describe alternatives you've considered

The altnernative is to do without turbo and manually copy all packages.json and yarn.lock files, and then the inputs.

**Comment by arlyon** [comment]
This is an cool request. I suppose what you are asking is for scopeless prune to only copy the input files into the new container. I think this is reasonable, I will raise it with the team and get a timeline.

**Comment by coryvirok** [comment]
+1 for base images with no scope. 

Also, I've been looking for a `--prod` flag for `turbo --prune --docker` that would only copy over the production workspace dependencies into `out/`. Without this type of flag, building lean Docker images requires a bunch of workarounds so they don't include all of the non-production workspace projects and all of the production workspace projects' source (vs built) code when transpiling from TypeScript.

More info here - https://github.com/vercel/turbo/issues/1100

**Comment by DesignByOnyx** [comment]
I wanted to offer a +1 and another use case for this. We deploy our app using both docker and bare metal (the latter is to support legacy clients who don't want to use docker... fml). For the bare metal clients, we use PM2 to launch all of our services from the same file system. 

Furthermore, to expand on the the `--prod` tag suggestion, could there be an option to only copy the "outputs" required for production? The dockerfile would look something like this:

```dockerfile
FROM base AS pruner
RUN turbo prune --docker

FROM base AS builder
COPY --from=pruner /app/out/json/ .
COPY --from=pruner /app/out/yarn.lock ./yarn.lock
# Full install
RUN yarn install
 
# Build the project
COPY --from=pruner /app/out/full/ .
RUN yarn turbo run build

# Now do the "prod" prune - only keep "prod" dependencies and "outputs" as configured in turbo.json
RUN turbo prune --prod --outputs --out-dir release

FROM base AS prod
COPY --from=builder /app/release ./
# This is only necessary if the prod image is a different OS than the builder stage
RUN yarn rebuild
```

**Comment by anthonyshew** [comment]
Hi, all! We just talked about this issue as a team and figured out we're going to mark it as a `wontfix` after looking at the use cases being described here. A few thoughts:
- It sounds like folks are wanting to make a base image to speed up the installation step for the subsequent images. We're looking at creating a `turbo install` feature that would dramatically speed up installing packages. It's highly likely this feature will solve the same problem in a different, more Turborepo-ish way.
- I'm seeing the `--prod` flag mentioned. That's a bit of a different concern and being discussed in #1100, as mentioned.

Perhaps the larger concern: This feature would encourage users into CI anti-patterns:
- Non-build jobs shouldn't be done in a Docker container. Those are jobs that your CI should handle as separate work from the build of the Docker container.
- The mental model for a Turborepo is to always do as little work as possible so that your CI stays fast. Installing the entire repository's dependencies when you want to rebuild one application would stray away from our goals.
- Placing multiple applications into one container is generally a Docker anti-pattern.

Given that this issue falls somewhere in between misfeature and anti-pattern, we're going to close it. Be on the lookout for `turbo install`!

**Comment by anglinb** [comment]
This is totally a hack but it seems to work for me. I just prune to all scopes:

```
yarn workspaces list --json | grep -v '"location":"."' | jq -r '.name' | xargs echo "turbo prune --docker"
```
