### ISSUE TITLE
[turborepo] not working with platform : win32 ia32 LE

### ISSUE THREAD

**Issue by niiyy** [vercel/turbo#4167]
### What version of Turborepo are you using?

1.8.0

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

I have a friend who wants to help me on one of my projects which uses a monorepo architecture with turborepo and pnpm, however when trying to install the modules he comes across the following error, he tried to use `pnpm install --config.target_arch=x64` without success.

```sh
.../.pnpm/turbo@1.8.0/node_modules/turbo postinstall$ node install.js
│ E:\other\resources\NX\node_modules.pnpm\turbo@1.8.0\node_modules\tu
│     throw new Error(Unsupported platform: ${platformKey});
│           ^
│ Error: Unsupported platform: win32 ia32 LE
```

### Expected Behavior

It's supposed to install the dependencies

### To Reproduce

You must be on a win32 ia32 LE platform and try to install the dependencies on a project with turborepo,

### Reproduction Repo

https://github.com/niiyy/NX

**Comment by arlyon** [comment]
Hi! We unfortunately do not (and don't plan to) support 32 bit machines with precompiled binaries. OSX no longer supports it as of as of OSX Catalina (2019) and Windows as of Windows 10 (2020).

That said, just because we don't provide them, doesn't mean you can't compile them yourself, however it will be a bit of work setting up rust and go toolchains. Once you are set up, you should be able to just run `cargo build --release` in the `crates/turborepo` folder and then copy turbo.exe and go-turbo.exe onto your path.

Feel free to comment here if you want further guidance but I am closing this as wontfix for now :)
