### ISSUE TITLE
[turborepo] with-Rollup example "Error: @rollup/plugin-typescript: Couldn't process compiler options"

### ISSUE THREAD

**Issue by brownieboy** [vercel/turbo#4507]
### What version of Turborepo are you using?

1.8.8

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

with-rollup error in the repo's examples throws "Error: @rollup/plugin-typescript: Couldn't process compiler options" when trying to build.

Full error:

> ui:build: index.tsx → dist/index.js...
> ui:build: (!) Plugin typescript: @rollup/plugin-typescript TS6053: File 'tsconfig/react-library.json' not found.
> ui:build: [!] (plugin typescript) Error: @rollup/plugin-typescript: Couldn't process compiler options

That turbo/examples/with-rollup/packages/ui/tsconfig/react-library.json file doesn't exist.  It's referenced in file turbo/examples/with-rollup/ui/tsconfig.json:

```json
  "extends": "tsconfig/react-library.json",
```

Removing that line gets a bit further, but now stops at this error:

> ui:build: [!] Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)
> ui:build: Button.tsx (3:11)
> ui:build: 1: import * as React from "react";
> ui:build: 2: export var Button = function () {
> ui:build: 3:     return <button>Boop</button>;

So it's not configured for React, which is what the missing file was doing, I guess?

### Expected Behavior

Running `pnpm build` should build the example without errors.

### To Reproduce

Steps:
```bash
git clone git@github.com:vercel/turbo.git
cd turbo/examples/with-rollup
pnpm i
pnpm build
```

I tried updating to the latest turbo version `pnpm i turbo --save-dev -w` but same errors.

### Reproduction Repo

https://github.com/vercel/turbo/tree/main/examples/with-rollup

**Comment by tknickman** [comment]
Hey @brownieboy, thanks for the report! This was our fault, we weren't using the pnpm workspace syntax for workspace dependencies. Fix is here: https://github.com/vercel/turbo/issues/4507, but you can also fix this yourself by updating all of the workspace dependencies from `"{package}": "*"` to `"{package}": "workspace:*"`. 

This was breaking because `tsconfig` is a workspace package that stored the shared ts configs for the monorepo, and the rollup TS plugin was unable to resolve this due to the incorrectly specified dependencies.
