### ISSUE TITLE
[turborepo] new turbo.json schema can't be accessed in China

### ISSUE THREAD

**Issue by tjx666** [vercel/turbo#4618]
### What version of Turborepo are you using?

1.9.1

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

I need to set proxy to aceess the schema:

![image](https://user-images.githubusercontent.com/41773861/232714503-0ab60850-36d3-4214-b646-420c94ead1c7.png)

### Expected Behavior

need not set proxy.

### To Reproduce

See screenshot.

**Comment by frencojobs** [comment]
I don't think it's on turbo. I live in Myanmar and a good chunk of the internet is also censored here including all websites hosted on Vercel. It's likely because they banned all IPs related to Vercel due to the revolutionists using Vercel to host websites. All websites hosted on GitHub Pages and AWS Cloudfront are also blocked for the same reasons.

I'm aware that it's not exactly the same situation for a one-to-one comparison. But using a VPN has been my way of getting around this. After connecting to a VPN, you'll sometimes need to `⌘+P > JSON: Clear Schema Cache` or reload VSCode.

**Comment by tknickman** [comment]
Sorry about that - you can generate your own schema to reference locally using the `turbo-types` package:

The script is here: https://github.com/vercel/turbo/blob/main/packages/turbo-types/package.json#L7, and you can see how we use it here: https://github.com/vercel/turbo/blob/main/docs/package.json#L12.

This won't update automatically when we make changes (you would need to pull latest and regenerate the schema), but hopefully that can unblock you!

**Comment by tjx666** [comment]
I see https://www.schemastore.org/json/ had alread been a tuborepo schema, but it't just redirect to official schema. So, why not just publish it to https://www.schemastore.org/json/, that website does not blocked China. And seems the offivial schema had changed url recently, why it's not block China before.
