### ISSUE TITLE
More clear language for `outputs have not changed since previous run`

### ISSUE THREAD

**Issue by maschwenk** [vercel/turbo#4759]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

This message is a bit confusing and there's no references to it in the documentation. My best understanding of it is something like this:

A depends on B. A & B have `build` tasks defined in the standard way in `turbo.json`

```json
"build": {
      "dependsOn": ["^build"],
      "outputs": ["dist/**"]
    },
```

If I change the README of B, and that does not result in a new output in `dist` (or more specifically the hash of the output) , then we don't bother running `build` on A. The presumption being if A depends on B's `outputs` and the `outputs` don't change, we don't need to rebuild A.

### Describe the solution you'd like

If the above is accurate, I wonder how we could change the language to make it clearer, or if it would suffice to link to documentation that explains it. If it isn't accurate, then that might suggest we should change the language anyway 😄 .

If my description is accurate, perhaps it could say something like:

```Output hash for <package name>#build is unchanged, dependent task(s) [list of dependent tasks] will not run```
```Output hash for package_a#build is unchanged, dependent task(s) package_a#build will not run```

but maybe that's untrue?

### Describe alternatives you've considered

Read the source code.

**Comment by mehulkar** [comment]
This was confusing to me too, open to new language. This message means two things:

- There was a cache hit (i.e. inputs did not change)
- There is no need to _restore_ cache from the local `.turbo` folder (or `--cache-dir) or the remote cache, because the required outputs are already there. 

This is good because you save additional time from not having to unzip a tarball, and restore it in the place where you've configured `outputs` for the task. 

Does that make sense? If so, feel free to propose a different message or a place in the docs where this information can go!

**Comment by mehulkar** [comment]
I'm updating this language in https://github.com/vercel/turbo/pull/4952, feel free to provide any feedback there.

**Comment by mehulkar** [comment]
This was done in https://github.com/vercel/turbo/pull/5127

**Comment by maschwenk** [comment]
@mehulkar nice! The change regarding this issue as well as the other subtle string changes make a lot of sense. Thank you! Sorry for dropping the thread here!
