### ISSUE TITLE
[turborepo] ERR_PNPM_CANNOT_RESOLVE_WORKSPACE_PROTOCOL

### ISSUE THREAD

**Issue by vaynevayne** [vercel/turbo#5031]
### What version of Turborepo are you using?

latest

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

pnpm run release localily
 ERR_PNPM_CANNOT_RESOLVE_WORKSPACE_PROTOCOL
<img width="760" alt="image" src="https://github.com/vercel/turbo/assets/124666577/420990eb-5719-47be-8e9f-aafd902a0787">

### Expected Behavior

work well 

### To Reproduce

download example/design-system 
pnpm i 
 git commit -m 'first'
pnpm changeset  -> all none none 
pnpm install
pnpm release 
get error

**Comment by mehulkar** [comment]
Hey @vaynevayne, couple things:

- If you're starting from one of our examples, you'll have to rename the package names to something other than their defaults to be able to publish. The example repos we provide will not be publishable out of the box
- I tried to follow your steps and got an error on publish (which is expected, since publishing shouldn't work out of box), but I got the expected 404 error on publishing `@acme/core`. The `ERR_PNPM_CANNOT_RESOLVE_WORKSPACE_PROTOCOL` error you reference seems different. What version of pnpm are you using? Is this what you're trying to solve with #5048?

**Comment by vaynevayne** [comment]
@mehulkar hello

I released the package for the first time using changetset and monorepo+ pnpm
I have a lot of comments on my operation, and now I can't remember the specific reason. The other pr is because when I want to publish soul-eslint-config to npm, it prevents me from releasing it, so I just change it to *.
I have changed the pnpm version several times, from pnpm 7 to 8
