### ISSUE TITLE
[turborepo] [design-system] is real work ? 

### ISSUE THREAD

**Issue by vaynevayne** [vercel/turbo#5034]
### What version of Turborepo are you using?

lates

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

1. npm has not  @acme 
<img width="1054" alt="image" src="https://github.com/vercel/turbo/assets/124666577/6898805f-9c07-4e21-b25a-bdc1c92adf8a">

2. existspnpm-lock.yaml, but github/workflow is  use yarn
3.  if use yarn , when github action`error Couldn't find any versions for "eslint-config-acme" that matches "workspace:0.0.0"`
4. https://github.com/vaynevayne/design-system/actions/runs/5022770668/jobs/9006611347
5. 
6. if use pnpm , `error an error occurred while publishing @acme2/core: E404 Not Found - PUT https://registry.npmjs.org/@acme2%2fcore - Scope not found 
🦋  error `
https://github.com/vaynevayne/design-system/actions/runs/5022838740/jobs/9006754428

When the above is still not using changeset, there are more problems if using changeset pulish

### Expected Behavior

Delete example/design-system

### To Reproduce

github action

**Comment by acme** [comment]
Yes, please stop notifying me 🙏

**Comment by NicholasLYang** [comment]
Hi @vaynevayne, thanks for opening these issues. I'll be honest, I'm not fully understanding this issue. Could you clarify what exactly is going wrong? These examples are not meant to actually be published to npm, so any package prefixed with `@acme` won't publish because you'd need to have the acme scope on npm. 

Also, if this issue is related to the previous two that you opened, I'd ask that you only open one issue and edit the issue text with updates.
