### ISSUE TITLE
[turborepo] 

### ISSUE THREAD

**Issue by brynshanahan** [vercel/turbo#5453]
### What version of Turborepo are you using?

1.10.1

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Mac

### Describe the Bug

```json
{
  "pipelines":  {
    "build": {},
    "test": {
       "depdendsOn": ["^build", "build"]
    }
  }
}
```
I have three modules: `@org/c`, `@org/b` and `@org/a`. Package `@org/c` depends on `@org/b` which depends on `@org/a`. These package's **build** scripts don't depend on each other. But the test needs all the modules it depends on to be built. Running `yarn turbo run test --filter=c` will wait for `@org/b` to be built but not `@org/a` to be built even though it is used as a deep/transient dependency, my expectation would be that it waits for all deeply depended on modules to be built. Is that a correct expectation or is there another syntax that would give me the behaviour I'm expecting?

### Expected Behavior

If I depend on `^build` in a pipeline I expected it would wait for all deeply depended on modules to be built as well.

### To Reproduce

<img width="1269" alt="image" src="https://github.com/vercel/turbo/assets/37826020/e96fb282-c418-4342-b96f-e7a5a358cf9e">

I tried to create a codesandbox showing the issue but I couldn't get turbo working on csb at all

**Comment by mehulkar** [comment]
`test`, dependsOn: `^build` will only go one level deep. Since `build` itself is not depending on `^build`, you won't get that recursively nested dependencies. You can accomplish this with a fake node though:

```diff
{
  "pipelines":  {
    "build": {},
    "test": {
-       "dependsOn": ["^build", "build"]
+       "dependsOn": ["^build", "build", "topo"]
-    }
+    },
+    "topo": {
+      "dependsOn": ["^topo"]
+    }
  }
}
```

That `topo` task will create a dependency from `@org/c` -> `@org/b` -> `@org/a`.

This is documented here: https://turbo.build/repo/docs/core-concepts/monorepos/task-dependencies#dependencies-outside-of-a-task, but the title of that section is a bit confusing to me, so it's easy to miss.
