### ISSUE TITLE
[turbopack] SCSS/SASS Modules export variables

### ISSUE THREAD

**Issue by baptisteauduge** [vercel/turbo#5465]
### What version of Next.js are you using Turbopack in?

13.4.8

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

When trying use exported variables from a scss file (export in a `:export {}`), variables are `undefined`.

### Expected Behavior

Expecting to have the content of the variable exported in the SCSS file
***Working with WebPack***

### To Reproduce

```ts
import colors from '@styles/colors.module.scss'

... Component...

console.log("color", colors.red)

return <div>
{colors.red}
</div>;
```

console log prompt : `color undefined`

and in the scss file :

```scss
$red: red;

:export {
  red: $red;
}
```

**Comment by d-rubin** [comment]
I have a similar problem, I have an UI-libary where i declare my variables and have that package in my node modules. after Upgrading from next: 13.4.12 to 13.5.1  i get this error when I run next dev --turbo:
```
X ModuleBuildError: Error evaluating Node.js code
SassError: SassError: Undefined variable.
      ╷
    6 │       max-width: $container-base;
      │                  ^^^^^^^^^^^^^^^
      ╵
```

**Comment by valleywood** [comment]
I'm having similar problems not with exporting but with importing a scss file from a npm package into my Next.js repo as this:
This works fine with Webpack but fails with Turbo
`@import "~<@my-org>/<my-package>/theme/themeFunctions";`

Also tried to remove the ~sign as that's something just required by the old webpack import.

I guess that this is currently expected though since the current version says that sass/scss support is something that is probably going to be added in the future? 🤔 
 
https://turbo.build/pack/docs/features/css#scss-and-less

**Comment by ForsakenHarmony** [comment]
See https://github.com/vercel/next.js/issues/61322#issuecomment-1921772455

**Comment by cbratschi** [comment]
Any chance this gets added in 2025? We use this feature a lot to retrieve for instance Bootstrap grid settings.

**Comment by furai** [comment]
Any chance to revisit this? @sokra

**Comment by StefanOrzu** [comment]
I don't think it's a great idea to be forced to use css variables at runtime when there was a perfectly good solution to have them available at compile time via the `:export` syntax. Now if I want to use turbopack my code gets significantly messier when it comes to managing SCSS variables and having them available in SSR.
