### ISSUE TITLE
Support android

### ISSUE THREAD

**Issue by yhyadev** [vercel/turbo#5616]
### Which project is this feature idea for?

Turbopack

### Describe the feature you'd like to request

Support android and termux users

### Describe the solution you'd like

Add binaries for android

### Describe alternatives you've considered

Add binaries for linux arm64 because termux is a terminal emulator for linux

**Comment by kwonoj** [comment]
We don't have any plans to support turbopack binaries for android arm devices right now, but we're evaluating platform options continuously.

**Comment by gtbuchanan** [comment]
I realize this is an old issue, but I didn't want to create a new one knowing this was explicitly rejected.

I found that the current turbo linux-arm64 binary actually runs fine on arm64 Termux with some help. Issue 1 and 3 are likely easily resolved by turbo.

## Issue 1: Package Resolution

The turbo npm package doesn't resolve `process.platform` `android` to `linux`, so the `linux-arm64` package isn't available

### Workaround

Run `pnpm install --force` to download the linux-arm64 binary

## Issue 2: Bionic libc Preload Bypassed

Termux's Bionic libc preload seems to be bypassed somehow, so turbo fails to find `/usr/bin/env` that the pnpm shebang uses. This might just be a problem for me because I'm executing pnpm scripts via turbo.

### Workaround

Add a shim script at `~/.local/bin/pnpm` (and make sure `~/.local/bin` is in PATH):

```bash
#!/data/data/com.termux/files/usr/bin/bash
exec /data/data/com.termux/files/usr/bin/node \
     /data/data/com.termux/files/usr/lib/node_modules/pnpm/bin/pnpm.cjs "$@"
```

## Issue 3: Turbo Launcher Platform Detection

The turbo launcher itself detects android arm64 is "unsupported" and fails to run (probably a symptom of issue 1).

### Workaround

Set `TURBO_BINARY_PATH` to the resolved linux-arm64 binary path. Example:

```
TURBO_BINARY_PATH=$(pwd)/node_modules/.pnpm/turbo@2.9.5/node_modules/@turbo/linux-arm64/bin/turbo node_modules/.bin/turbo run my-task
```

This is the most inconvenient one if you're using a local turbo install since it must be set for every invocation. I am personally using my own wrapper around turbo to handle this for me.
