### ISSUE TITLE
[turborepo]  Problem during upgrade 

### ISSUE THREAD

**Issue by jandnil** [vercel/turbo#5617]
### What version of Turborepo are you using?

1.10.2 or above

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Windows

### Describe the Bug

build works perfect on 1.10.1 but upgrading turbo to any version > 1.10.1 gives the following error running a build:
 
 ERROR  run failed: error preparing engine: Could not find "___ROOT___#build" in root turbo.json
Turbo error: error preparing engine: Could not find "___ROOT___#build" in root turbo.json
 ELIFECYCLE  Command failed with exit code 1.

### Expected Behavior

run build as during 1.10.1 

### To Reproduce

I dont know it is something changing between 1.10.1 --> 1.10.2 runing pnpm 8.6.10 and node 20.X

**Comment by nathanhammond** [comment]
@jandnil none of these keys do anything inside of `turbo.json`:

```
"packageManager": "pnpm",
"pnpmStoreDir": ".pnpm-store",
"pnpmWorkspaceFile": "pnpm-workspace.yaml",
"pnpmLockfile": "pnpm-lock.yaml",
```

It sounds like you were experiencing a transient error? We're in the process of porting this graph walk to Rust at which point the output you're seeing here will no longer exist. Since it appears to be working for you now I'm going to close this out.
