### ISSUE TITLE
[turborepo] `~` single character package name causes parse error

### ISSUE THREAD

**Issue by jpulec** [vercel/turbo#5641]
### What version of Turborepo are you using?

1.9.4

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Linux

### Describe the Bug

It appears that if you use a single tilde character (`~`) as a package name, turbo's lockfile parsing fails. I'm guessing because it thinks it needs to parse it as a npm specifier?

### Expected Behavior

You should be able to use `~` as a package specifier.

### To Reproduce

Add a package.json like the following:

```json
{
  "name": "test",
  "dependencies": {
    "~": "link:./src"
  }
}
```

And then try to run `turbo run` or `turbo prune` that task.

**Comment by chris-olszewski** [comment]
It looks like `yarn` is encoding dependencies on `~` as `~: "workspace:*"` in `yarn.lock`. This causes issues as according the the YAML spec [`~` is equivalent to `null`](https://yaml.org/refcard.html). This causes the YAML parser we're using to trip up. I can try to massage `~` to not be a null value, but my recommendation would be to avoid using `~` as a package name since it is a special scalar according to the YAML spec.

**Comment by nathanhammond** [comment]
Hey @jpulec! This isn't something that we intend to support given that we're riding on the rails of the JavaScript ecosystem and `~` is not a valid package name: https://github.com/npm/validate-npm-package-name#naming-rules

Our official recommendation is indeed to use a different package name.
