### ISSUE TITLE
[turborepo] False flag as Trojan:Win32/Bearfoos.A!ml

### ISSUE THREAD

**Issue by biw** [vercel/turbo#5649]
### What version of Turborepo are you using?

1.10.12

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Windows

### Describe the Bug

On running `yarn turbo` I am getting the following error from Windows Defender (Windows 10 Pro):

<img width="530" alt="Screenshot 2023-07-31 at 11 30 06 AM" src="https://github.com/vercel/turbo/assets/6139501/fc938938-0a39-44a4-a183-896368815670">

```
Trojan:Win32/Bearfoos.A!ml
```

### Expected Behavior

Expect it not to be flagged as a Trojan by Windows Defender.

### To Reproduce

```
mkdir turbo-test
cd turbo-test
yarn init .
yarn add -D turbo
yarn turbo start
```
Result:
```
Error: Operation did not complete successfully because the file contains a virus or potentially unwanted software. (os error 225)
```

**Comment by nathanhammond** [comment]
We would need to investigate signing our binaries in order to do something about this. Since this is flagging our Go binary (which we're in the process of removing) I'm going to close this as something that we're not going to pursue. Hopefully the definitions for that have since been revised and it is no longer getting flagged. You can also try more-recent Canary versions which may also sidestep the signature that it is looking for.
