### ISSUE TITLE
[turborepo] Codegenerator not support ESM

### ISSUE THREAD

**Issue by peam1146** [vercel/turbo#5657]
### What version of Turborepo are you using?

v1.10.9

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Mac

### Describe the Bug

```
Unexpected error. Please report it as a bug:
Must use import to load ES Module: /Users/peam/work/softnetics/<app>/turbo/generators/config.ts
require() of ES modules is not supported.
require() of /Users/peam/work/softnetics/<app>/turbo/generators/config.ts from /Users/peam/.npm/_npx/111d46748c4e70c7/node_modules/node-plop/lib/node-plop.js is an ES module file as it is a .ts file whose nearest parent package.json contains "type": "module" which defines all .ts files in that package scope as ES modules.
Instead change the requiring code to use import(), or remove "type": "module" from /Users/peam/work/softnetics/<app>/package.json.
```

I got this error when use "type: 'module'" in package.json

### Expected Behavior

It should work ...

### To Reproduce

use "type: 'module'" in package.json

**Comment by peam1146** [comment]
It works when I use .cjs with jsDoc instead

**Comment by tknickman** [comment]
This is a known limitation at the moment, we're working to provide full support for ESM dependencies in the future!

**Comment by Nilegfx** [comment]
I think this is an important feature as it blocks us from having code generation in `type: module` packages. even if we tried the suggested workaround in @allejo  comment above, we still have to change all import statements down the flow to CJS imports too. this is very annoying issue.

**Comment by wesleycoder** [comment]
I was digging into this issue and found out that adding a `package.json` with `"type": "commonjs"` to `turbo/generators` is enough to resolve this issue, so I filed the PR above.

While this is not merged if anyone stumbles into this you can create the file by hand, including on already existent templates without the need to convert the `config.ts` or `config.js` to `commonjs` format.

#typesafety_ftw

**Comment by paolostyle** [comment]
Why is this issue closed? My entire codebase is in ESM format and this silly workaround with package.json is not a solution. At the very least this should work with a config.cts/config.cjs file.

**Comment by wesleycoder** [comment]
AFAIK the support for ESM should come from the underlying [plopjs/plop](https://github.com/plopjs/plop) package and turborepo has no way of supporting this on it's own.
Consider opening an issue there if this continues to impede your use-case/workflow.

**Comment by paolostyle** [comment]
I ended up using plop directly. Turborepo is using version 0.26.0 of `node-plop` (latest is 0.32.0, due to semver it's stuck at 0.26.0 despite the `^`) which I presume does not support ESM, but the latest versions of `plop` packages are ESM-based. I tried overriding the version of `node-plop` through `pnpm.overrides` but that didn't help either. I don't see a lot of value in using Turbo's wrapper anyway.

**Comment by umar-ahmed** [comment]
> latest is 0.32.0, due to semver it's stuck at 0.26.0 despite the `^`

@paolostyle Caret behaves differently for 0.x.y version ranges. It will never upgrade past 0.26.x

@wesleycoder are there any plans to upgrade the version of Plop within Turborepo? I think it might resolve the issues that people like me are having with the way turbo gen handles ESM files 🙏

**Comment by paolostyle** [comment]
I know how it behaves, that's what I meant by "stuck", but I suppose I didn't express my thoughts properly, sorry about that.

**Comment by goszczynskip** [comment]
This shouldn't be closed. Currently, there's no option to load any ESM package to the generator because Plop does not support async generators. You cannot load it directly or with import() syntax when putting package.json with the module type "commonjs." So, switching module type is just a partial fix that allows ESM dependency-free generators to run. 

I don't see an easy way to create a workaround here. @turbo/gen is loaded via npx from turbo rust code. So project-level overrides won't work, and code pnpm/yarn package patching either. The only option for now is to change turbo sources and build a modified version locally which adds too much complexity.

If there are no plans on updating the plop-node version what I'd propose is to respect the project's @turbo/gen dependency instead of always reaching for the one from npx. This will allow for overrides to work at least

**Comment by azezsan** [comment]
> This shouldn't be closed. Currently, there's no option to load any ESM package to the generator because Plop does not support async generators. You cannot load it directly or with import() syntax when putting package.json with the module type "commonjs." So, switching module type is just a partial fix that allows ESM dependency-free generators to run.
> 
> I don't see an easy way to create a workaround here. @turbo/gen is loaded via npx from turbo rust code. So project-level overrides won't work, and code pnpm/yarn package patching either. The only option for now is to change turbo sources and build a modified version locally which adds too much complexity.
> 
> If there are no plans on updating the plop-node version what I'd propose is to respect the project's @turbo/gen dependency instead of always reaching for the one from npx. This will allow for overrides to work at least

I agree I don't know why this closed, even the default turborepo example doesn't work

**Comment by pauliesnug** [comment]
This got broken again I think, why is this closed?

**Comment by limwa** [comment]
I managed to find a work-around for this if anyone is interested!

Since, my `packages/example/package.json` has `{ "type": "module" }`, I am experiencing the same problem as everyone in this thread. To be able to continue having my package as a module and still have working generators, I created `packages/example/turbo/package.json` with the following content:

```json
{
  "type": "commonjs"
}
```

Then, the generator is defined in `packages/example/turbo/config.ts`.

For now, I haven't found any problems with this setup. My packages are all ESM-based and the generators are recognized and can be executed by `turbo gen`.

**Comment by sidletski** [comment]
It's honestly strange this issue still exists in v2.5, especially since it could be easily hack-fixed by just placing another package.json inside the turbo folder
But since the turbo generators are built on top of [plop](https://github.com/plopjs/plop) anyway, I'd suggest switching config from `.ts` to `.mjs` and use plop directly. E.g.:
```json
"generate": "plop --plopfile ./turbo/generators/config.mjs"
```

You can keep types using JSDoc like this:
```js
export default (
  /** @type {import('plop').NodePlopAPI} */
  plop
) => {
  // your generator here
};
```

**Comment by codinsonn** [comment]
> It's honestly strange this issue still exists in v2.5, especially since it could be easily hack-fixed by just placing another package.json inside the turbo folder But since the turbo generators are built on top of [plop](https://github.com/plopjs/plop) anyway, I'd suggest switching config from `.ts` to `.mjs` and use plop directly. E.g.:
> 
> "generate": "plop --plopfile ./turbo/generators/config.mjs"
> You can keep types using JSDoc like this:
> 
> export default (
>   /** @type {import('plop').NodePlopAPI} */
>   plop
> ) => {
>   // your generator here
> };

How would we still import our .ts based generators then? Would we not have to transform those to .mjs as well or compile them to .js first? Seems like an impactful workaround...

**Comment by mifrej** [comment]
This issue is still occuring in 2.5.3
