### ISSUE TITLE
[turborepo] Cache miss for workspaces with no defined task and no changes

### ISSUE THREAD

**Issue by closesimple-wl** [vercel/turbo#5808]
### What version of Turborepo are you using?

1.10.12

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Implementing the pattern where it's the responsibility of "apps" workspaces to bundle package code, described here: https://turbo.build/blog/you-might-not-need-typescript-project-references

Therefore we have a "build" task that is not defined in "packages" workspaces.  Because the "build" task is undefined for packages, obviously there are no `outputs` as specified in the task.  The only possible output is the console output, which again, there is none because the packages don't define the `scripts` definition.

I'm able to define:
```json
"scripts": {
    "build": "echo cache this"
}
```
...the "build" script in the packages to force this to work as expected, but I shouldn't have to.

### Expected Behavior

When nothing is cached (no `outputs`, empty console string) and the `inputs` haven't changed, that should be considered a cache HIT.

### To Reproduce

1. Use `pnpm dlx create-turbo@latest` as described here: https://turbo.build/repo/docs/getting-started/create-new
1. `turbo build`
1. `turbo build --dry=json > dryRun.json`
1. Search the "dryRun.json" file for "MISS"
1. The three "packages" without a "build" defined in their "scripts" report "MISS"
1. Add a dummy "build" script as defined above.
1. `turbo build`
1. `turbo build --dry=json > dryRun.json`

"MISS" is no longer reported for the packages, which should be the default behavior.

### Reproduction Repo

`pnpm dlx create-turbo@latest` demonstrates this easily enough.

**Comment by arlyon** [comment]
Hello

Caching issues are usually quite hard to repro without an example. Are you able to provide a repo I could look at?

Thanks fo taking the time to report

Alex

**Comment by closesimple-wl** [comment]
I'll try to throw something up.

The behavior of `turbo build` is different than `turbo build --dry=json > dryRun.json`, where the dry run consistently reports cache MISS for the packages, whereas after the first `turbo build`, subsequent `turbo build` commands report "FULL TURBO" AKA HIT for all.

That's just further evidence that this is a bug, possibly only in dry run, which is critical for us.

**Comment by closesimple-wl** [comment]
The template monorepo generator reproduces this.

**Comment by nathanhammond** [comment]
One quick note: your test procedure is modifying files in directory (`dryRun.json`) which can cause surprising behavior. I strongly recommend putting those outside of the directory when attempting to debug caching issues.

***

In this case, your concern appears to be about presentation.

> The three "packages" without a "build" defined in their "scripts" report "MISS"

This is still a miss: we did not find the contents in the cache _because there was nothing to load_. We create a log artifact (even if it is `""`) so long as there is a script. But if there is no script, we don't attempt to run a task, we don't create a cache artifact. So when we go to look for it in the cache it's a "MISS." It's a `HEAD` call to the remote cache (`404`) and `stat` on the disk (`ENOTFOUND`). That's a miss.

Note that `--dry=json` manually inspects the cache state for a particular hash, isolated from a run to get bonus information, `turbo build` does not perform that check because it simply attempts to use it, and if it fails it proceeds to run the task.

"FULL TURBO" refers to the fact that, of all commands that were executed, their results were all pulled from cache. A package not implementing a script does not mean that you can never be "FULL TURBO".

It does not appear that this distinction is materially affecting your runs, and it also does not appear that you're attempting to use this distinction in order to do other processing (and you would in fact need this information to do further processing) so I'm closing this out.

**Comment by closesimple-wl** [comment]
> It does not appear that this distinction is materially affecting your runs, and it also does not appear that you're attempting to use this distinction in order to do other processing (and you would in fact need this information to do further processing) so I'm closing this out.

Let the user determine whether the issue is material to them.  Also give me a chance to respond before closing.  Put me on a timer for all I care. #timeout

This does materially affect us.  We're not using a remote cache (yet), so each CI, we build a local cache (`turbo build`), pull the latest code version, and use `turbo build --dry=json` to detect change.  Only changed projects are deployed.  Basically what https://turbo.build/repo/docs/core-concepts/monorepos/skipping-tasks does with `--fallback`, except we're not using that dependency since it's hard to decipher the docs (no output specified, anyone?), which are tightly married to assuming Vercel platform usage.  Cognitive load++.

> _because there was nothing to load._

From the user perspective, I don't care what your implementation details are.  All I care about is cache MISS = something must have changed.

**Comment by closesimple-wl** [comment]
@nathanhammond

**Comment by closesimple-wl** [comment]
@nathanhammond what do you think, now that I've provided more information, after the premature closing of this issue?

If you want to keep the literal semantics of the `cache.status` property, you can introduce a new flag that indicates what a user requires.

**Comment by nathanhammond** [comment]
Cache miss doesn't mean "something has changed." It means that "attempting to look up the item in the cache has failed." You're attempting to gain data about the behavior of an unobserved run based upon the observability of a side effect.

Given that there are any number of reasons a cache can miss, if you want to determine which projects to deploy you should instead be doing a task hash comparison across two dry runs: old hash (for deployed state) is X, new hash is Y. This is precisely what turbo-ignore does and you need to either use that, or recreate it.

Aside: turbo-ignore doesn't run a build. It just tells you whether or not you need to run one. It's in use many places that aren't Vercel's platform.

***

I closed the issue because we won't be changing the behavior for the cache metadata or making it configurable. We don't consider it to be a bug.

**Comment by closesimple-wl** [comment]
Really all that would be needed to fix this is a new status `cache.status = "NOT USED"`.  If there's nothing to cache, which you know ahead of time, there's no reason to do a cache lookup and produce the boolean status.

**Comment by dBianchii** [comment]
I landed here after trying to do the same:
- I need to cache a no-op in my CI with `pnpm turbo deploy` for example.
- This deploy script is just an "echo 'this does nothing'". I just use this to mark something to the remote cache as "deployed".
- Then I attempt to read this remote cache with `--dry=json`, filtering for the task and getting the cache status. but I really never get a 'HIT'.

How can I make my setup work? I believe it is similar to yours @closesimple-wl
