### ISSUE TITLE
[turborepo/docs] package can be both internal and external

### ISSUE THREAD

**Issue by llllvvuu** [vercel/turbo#5844]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

It's possible to make an internal package which converts to an external package when it's packaged, using a tool like `clean-package`. See here for an example:

https://github.com/cschroeter/park-ui/blob/main/packages/presets/package.json

### Describe the solution you'd like

Tweak some of the docs language like "Internal packages are [packages](https://turbo.build/repo/docs/handbook/sharing-code) which are only intended to be used inside your monorepo" and mention the internal+external recipe. It's not obvious where this would go in the sidebar hierarchy and there are a couple of ways one could go about it, so I'm opening an issue before trying anything. 

### Describe alternatives you've considered

Leave as-is.

**Comment by chris-olszewski** [comment]
If I'm understanding the ask I think we'd accept/consider a PR that includes a mention of `clean-package` in either [publishing packages](https://turbo.build/repo/docs/handbook/publishing-packages) or the [versioning and publishing](https://turbo.build/repo/docs/handbook/publishing-packages/versioning-and-publishing) subpage. I'm not sure that I see this as a new internal+external recipe that requires a special mention in the primary docs. It looks like `clean-package` would be used for external packages, but it just cleans them up before publishing. I might be misunderstanding it though so please correct me if I'm missing something key.

**Comment by llllvvuu** [comment]
To explain the setup a bit more, it involves putting index.ts as "main" (thus making it an internal package) but swapping it out for index.js in prepack / restoring it to index.ts in postpack (thus packing it as an external package). The downside of this method is that it's technically not guaranteed that your internal developers and external consumers will see the same thing.

**Comment by chris-olszewski** [comment]
Okay, I don't think this is a scenario that we need to specifically call out in our documentation. Since it can be accomplished by either having multiple `package.json` or by changing your other workspaces consume this package as an external one. The latter is probably preferable as it means that internal and external use of the package is consistent.

**Comment by leograde** [comment]
It might however be very helpful to have at least an example of a project set up in that fashion.

For example, when a package is configured with only one package.json that points to dist/índex.js which means it needs to properly be built before being consumed by another internal package. Depending on the lint rules, you can end up running lint in parallel with build and get import/no-unresolved errors.

This is fixed by adding a ^build dependency to the lint task in turbo.json.

We had this issue in the company I work for this week and I would have loved to see some more information on how to deal with packages that are both consumed externally and internally.

Let me know whether this makes sense as I'm pretty new to Turborepo.

Thanks!
