### ISSUE TITLE
[turborepo] Cross packages; cannot find module or declarations

### ISSUE THREAD

**Issue by FlorianBurgevin** [vercel/turbo#5845]
### What version of Turborepo are you using?

latest

### What package manager are you using / does the bug impact?

npm, pnpm

### What operating system are you using?

Mac

### Describe the Bug

Hello.

I'm trying to build a Design System with Turbopack monorepo.

I'm facing a problem in local when i use my packages in other ones or in apps.

You can reproduce the problem with the examples repos like https://github.com/vercel/turbo/tree/main/examples/with-changesets

I start with `pnpm i`.
Then, if you go in the IDE (IntelliJ for me) to `apps/docs/src/app/page.tsx`. The IDE says that he can't find the Button module.
`TS2307: Cannot find module  @acme/core  or its corresponding type declarations.`

That's because the `package.json` of the button package says:
```
  "main": "./dist/index.js",
  "module": "./dist/index.mjs",
  "types": "./dist/index.d.ts",
```

In local i didn't build all my application, i just want to launch the local app (or the storybook for DS).

I have the same problem if i use one of my packages in an other package.

So my question is, what is the correct way to use cross-packages in my monorepo.
Should I change the path in `package.json` ? But it will break when i publish to npm ?
Should I need to build before using my app ?
Another solution ?

Thanks !

### Expected Behavior

I shouldn't have error in local with the importation of my packages.

### To Reproduce

- Clone  https://github.com/vercel/turbo/tree/main/examples/with-changesets
- pnmp i
- Go to your IDE in `apps/docs/src/app/page.tsx`

You should have a TS error.

### Reproduction Repo

https://github.com/vercel/turbo/tree/main/examples/with-changesets

**Comment by ahsath** [comment]
i have a similar issue and is not a bug, having said that i haven't find a solution or workaround either, the thing is that on dev usually you point your `"main"` and `"types"` to the your app entry point e.g. `main.ts` but if it is the case (my case) that you also need to build and deploy the UI library that is shared for other workspaces on dev `app, docs, etc`, users of your UI library will import `"main.ts"` file instead of your intended `"./dist/index.js"` which is probably not what we want, this is explained in turborepo's [bundling section](https://turbo.build/repo/docs/handbook/publishing-packages/bundling).

one thing you can do is keep your config as it is and depending on your bundler you can build your UI lib on dev with a watch command, e.g.

```JSON
// Vite as bundler

{
  "main": "./dist/index.js",
  "module": "./dist/index.mjs",
  "types": "./dist/index.d.ts",
  "scripts": {
    "dev": "vite build --watch" // or your bundler build command
  }
}
```

**Comment by tknickman** [comment]
You can also work around this with `typesVersions`:

https://github.com/vercel/turbo/issues/4771#issuecomment-1587351163
