### ISSUE TITLE
linux-arm (Raspberry Pi) and linux-ppc64le (Raptor CS Talos 2/Blackbird) support

### ISSUE THREAD

**Issue by darkbasic** [vercel/turbo#5957]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

turbo is not multi platform anymore and I've already had to abandon it in several projects due to this.

See https://github.com/vercel/turbo/issues/2616
and https://github.com/vercel/turbo/discussions/1891#discussioncomment-3913339

### Describe the solution you'd like

Turbo should support all major platforms.

### Describe alternatives you've considered

I've already had to move to yarn 4 (which integrates a brand new task runner) in several projects. I'd rather like to be able to use turbo.

**Comment by nathanhammond** [comment]
Platform expansion is something that is not going to be considered until we finish removing Go from our codebase. Once we are in a pure Rust codebase it is something we would consider in PR form based upon our feelings about the likely complexity of ongoing maintenance. The PR would just need to demonstrate getting a working build on GitHub Actions, not the full automated release process.

We have discovered that the cost of maintaining just the right versions of dozens of tools to end up with a working build is extremely high and grows relative to the infrequency of use of the platform.

Uncommon platform? Generally many times more difficult.

We already have to support tool chains for:
- glibc/musl/msvc
- win/darwin/linux
- arm64/x64

We had to use zig cc to make it work. And that's just to support the six we currently support.

I'm closing this because we are not intending to address it short term, and long-term we would be looking for community support.

**Comment by darkbasic** [comment]
> The PR would just need to demonstrate getting a working build on GitHub Actions

That wouldn't be hard to achieve, I could do that. May I ask to keep this open to track the progress? Maybe adding a "waiting for rust" tag or something similar. Thanks.
