### ISSUE TITLE
[turborepo] incorrectly links eslint

### ISSUE THREAD

**Issue by popuguytheparrot** [vercel/turbo#5995]
### What version of Turborepo are you using?

1.10.14

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Mac

### Describe the Bug

webstorm does not see the eslint package after installing dependencies in turborepo. This is manifested by an error in the editor saying that the eslint process cannot be started because the path to it does not exist

### Expected Behavior

the dependency will be available for selection

### To Reproduce

1. use webstorm
2. yarn dlx create-turbo@latest
3. open page.tsx and run Fix ESLint Probles
4. see on error badge of top on editor

**Comment by nathanhammond** [comment]
Yarn 3 uses `PnP` by default. `turbo` doesn't involve itself in the package resolution, it simply completes the installation. In this case, `eslint` does not specify `preferUnplugged`, and WebStorm is failing to find the binary because it doesn't exist as a separate file on disk.

This is not a `turbo` problem. You can either choose a different package manager, or a different installation strategy for Yarn 3 to work around WebStorm limitations.

**Comment by popuguytheparrot** [comment]
For those who encountered such a problem with to do create yarnrc, where nodelinker set node-modules
