### ISSUE TITLE
[turborepo] pnpm's shared-workspace-lockfile=false triggers a warning

### ISSUE THREAD

**Issue by buzinas** [vercel/turbo#6024]
### What version of Turborepo are you using?

1.10.14

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Mac

### Describe the Bug

Using pnpm's `shared-workspace-lockfile=false` triggers a warning:

```bash
 WARNING  Issues occurred when constructing package graph. Turbo will function, but some features may not be available:  1 error occurred:
        * error performing lockfile operation: Unable to convert to yaml: missing field `importers`
```

PS: by checking the code, I can see that most properties are optional / have their serialization skipped when they're not present, but `importers` for some reason is required (and it doesn't exist when `shared-workspace-lockfile` is `false`).

https://github.com/vercel/turbo/blob/2bb8c9a2477b5fb20b4711fe34412559bc85aab9/crates/turborepo-lockfiles/src/pnpm/data.rs#L27

### Expected Behavior

Using pnpm's `shared-workspace-lockfile=false` should just work™.

### To Reproduce

1. Follow the tutorial, create a new monorepo: `pnpm dlx create-turbo@latest`.
2. Open the folder: `cd ./my-turborepo`.
3. Edit the `.npmrc` file and add `shared-workspace-lockfile=false`.
4. Run `pnpm i` so it updates `pnpm-lock.yaml`.
5. Run `turbo run lint` and the warning shows up.

### Reproduction Repo

https://github.com/buzinas/turborepo-importers-bug

**Comment by chris-olszewski** [comment]
Is there something preventing you from using a single `pnpm-lock.yaml` for your project? 

Also, if you include `pnpm-lock.yaml` in your [task input](https://turbo.build/repo/docs/core-concepts/caching/file-inputs#workspace-files) (this is true by default if you aren't specifying explicit "inputs") you're actually getting the correct behavior since `turbo` will treat any change `pnpm-lock.yaml` as a change to the workspace that contains it.

Closing due to supporting this config option fully would take a fair amount of effort and our fallback behavior ends up doing the correct thing. Feel free to reopen if I'm misunderstanding or if there's additional things that are broken.

**Comment by buzinas** [comment]
My project consists of a single private monorepo with multiple private workspaces but a few open source workspaces that have their own repo using [`git subrepo`](https://github.com/ingydotnet/git-subrepo). These workspaces need their own `pnpm-lock.yaml` files, as they can also be used as standalone projects (independent of the monorepo).

**Comment by andredezzy** [comment]
@buzinas any news about how to solve this warning?

**Comment by michaelschufi** [comment]
@chris-olszewski Thank you for the explanation!

>Also, if you include pnpm-lock.yaml in your [task input](https://turbo.build/repo/docs/core-concepts/caching/file-inputs#workspace-files) (this is true by default if you aren't specifying explicit "inputs") you're actually getting the correct behavior since turbo will treat any change pnpm-lock.yaml as a change to the workspace that contains it.

Does this mean most turborepo commands should work without issues (most importantly build scripts ofc)? Looking at #3541, I wonder how this setting affects commands. In what cases should we pay extra attention because of `shared-workspace-lockfile=false`?

Also, I just want to throw in a rather unfortunate behavior in monorepos with older projects inside with`shared-workspace-lockfile` enabled: https://github.com/pnpm/pnpm/issues/7158
AFAIK, this is currently the best/most robust option to work around those issues with pnpm and tsc. This is why we are using the setting.

**Comment by hooper-hc** [comment]
Ideally, the projects in the repository are all from the same period and have similar dependencies, so I can share locks, which is more convenient.

However, in reality, I create a repository with new projects and old projects migrated in a few years ago. If I don't close the share lock, there will be endless troubles.

When any team connects to turborepo, I will immediately close the share lock file: shared-workspace-lockfile=false

**Comment by LinnJS** [comment]
I am getting this same issue on turbo latest, the main reason we are not using a single lock file is due to needing to support many apps and not have package versions couples so we can upgrade certain apps and ship them with newer code than others.
