### ISSUE TITLE
[turborepo] With-tailwind example won't watch tailwind.config changes

### ISSUE THREAD

**Issue by mareksupruniuk** [vercel/turbo#6054]
### What version of Turborepo are you using?

1.10.14

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

It seems turborepo (nextjs) dev server does not correctly watch `tailwind.config.ts` changes when the config file is located in another package. The output css file is not updated (`apps/web/.next/static/css/layout.css`).
After manually restarting server, changes are present.

If `tailwing.config.ts` file is not imported from `packages/tailwing.config.ts`, but is defined directly in `apps/web`, any changes to tailwind config are correctly recognized by the dev server, and web app receives an updated css file.

### Expected Behavior

Whenever `tailwind.config.ts` or its import files change, dev server compiles and updates css files. Manual server restart is not required.

### To Reproduce

1. clone `https://github.com/vercel/turbo/tree/main/examples/with-tailwind` repo
2. run the app `yarn dev`
3. update `packages/tailwind-config/tailwind.config.ts` file (for instance, the gradient color) - the app does not see any updates
4. restart dev server manually - changes are available

optional steps, to reproduce correct behaviour:
1. copy `packages/tailwind-config/tailwind.config.ts` to `apps/web/tailwind.config.ts`
2. run the app `run dev`
3. update `apps/web/tailwind.config.ts`  - nextjs sees the changes and web app receives updates

### Reproduction Repo

https://github.com/vercel/turbo/tree/main/examples/with-tailwind

**Comment by nathanhammond** [comment]
```
pnpm dlx create-turbo@canary issue-6054 --example with-tailwind --package-manager pnpm
code issue-6054
cd issue-6054/apps/web
turbo build
next dev
```

Multiple issues here:
- `next dev` fails if not invoked via `turbo dev`.
- `next` doesn't detect and reload `packages/tailwind-config/tailwind.config.ts` through a workspace.

**Comment by Neosoulink** [comment]
Hey @nathanhammond, @mehulkar.
Is someone working on this issue?

I can work on it

**Comment by mehulkar** [comment]
Hey @Neosoulink thanks for the ping, I don't think anyone's actively working on it, but @anthonyshew can help shepherd in any changes that might be appropriate!

**Comment by Neosoulink** [comment]
Hello @mehulkar @nathanhammond @anthonyshew,

I tried to work on this issue today and I think this is not related to Turborepo, but Next or more precisely to the NextJS **webpack** configuration.

All the packages imported into the folder `./src` are well detected, but not the packages imported from the root.
Even after I tried to update the `watch` and `watchOptions` webpack properties into `next.config.ts`, the result remained the same.

But, there's a small trick (which I don't really like), is to set a **relative path** at the importation
E.g: `import sharedConfig from "../../packages/tailwind-config/tailwind.config.ts";`

By doing that, changes will be detected
cc: @mareksupruniuk

---

@nathanhammond, I'm sure the command failed because of the version of your global `next` and the project `next` version

Here I tried to run the project with the global `next` at version `14.x.x` and the project `next` at version `^13.x.x` and got an error
![image](https://github.com/vercel/turbo/assets/44310540/65580869-49b9-4a6c-b3e3-ff210c055309)

However after I updated the version of the project to the same version of the global `next`, all worked fine (which means at version `14.x.x`)
![image](https://github.com/vercel/turbo/assets/44310540/aa190d26-d107-4ba2-93f2-a09ecddc6362)

---

> Maybe I missed some configuration or other details, please if you have more information about the way NextJs watches file changes, I would really appreciate receiving them🙏
I did not go too deep inside NextJs to see how it works and how webpack was configured 😔

**Comment by anthonyshew** [comment]
The `with-tailwind` example is receiving some upgrades in #6575.

However, we still won't be able to watch the packaged Tailwind configuration file since it is a simple export with no way to file-watch on it. In my research, the `tailwindcss` CLI doesn't watch for changes in the config files in the `extends` key.

If you'd like to see a Turborepo solve for this, follow along with/add a reaction to #986.

**Comment by mehulkar** [comment]
Going to close this down since the tailwind example part of this is as resolve as it's going to get. Apologies we don't have better news for you at the moment @mareksupruniuk and everyone else!
