### ISSUE TITLE
Create an example using import aliases inside projects

### ISSUE THREAD

**Issue by volnei** [vercel/turbo#6291]
### Which project is this feature idea for?

Turborepo

### Describe the feature you'd like to request

Curretly is too dificult to get path aliases working in turborepo, I've tryed in many ways with no success. 

### Describe the solution you'd like

An example using path aliases that works

### Describe alternatives you've considered

Disabling eslint is a terrible solution.

**Comment by Southclaws** [comment]
+1 on this, I've run into this today after trying --turbo again in Next. Because I have one alias for Panda's generated styles, I'll either have to figure out how to make the alias work or move my files (or just wait until the next release to try --turbo lol)

```js
experimental: {
    turbo: {
      resolveAlias: {
        "@/styled-system/*": "styled-system/*",
      },
    },
  },
```

The [docs here](https://turbo.build/pack/docs/features/customizing-turbopack#resolve-aliases) imply this may work due to the reference to "similar to webpack's [resolve.alias](https://webpack.js.org/configuration/resolve/#resolvealias)"

**Comment by timneutkens** [comment]
You don't have to add Turbopack specific config for this, you can add a `jsconfig.json` or `tsconfig.js`  `paths` config which is automatically respected: https://nextjs.org/docs/app/building-your-application/configuring/absolute-imports-and-module-aliases#module-aliases

**Comment by richardtaylordawson** [comment]
Curious what the resolution was here? 

I am in the same boat as the others. I have a `jsconfig.json` in the root of the NextJS app, but thats in a Turborepo project. Everything runs fine, however, eslint gives warnings that it cannot resolve the paths despite putting in the settings of `import/resolver` what those aliases are. Maybe I'm slightly off, but I feel like I've tried everything 🫠

**Comment by dennisbhexa** [comment]
same here, resolveAlias is not working when the path is app relative 
`
    experimental: {
        turbo: {
            resolveAlias: {
                '@/*': './*',
            },
        }
    }
`
getting module not found error
