### ISSUE TITLE
[turborepo] jest cannot resolve the 'ui' directory in the `with-create-react-app` example

### ISSUE THREAD

**Issue by kateEcobb** [vercel/turbo#6518]
### What version of Turborepo are you using?

latest

### What package manager are you using / does the bug impact?

Yarn v1

### What operating system are you using?

Mac

### Describe the Bug

I made a fresh clone of https://github.com/vercel/turbo/tree/main/examples/with-create-react-app, ran `yarn install`, made a copy change within the `web` directory (in order for jest to recognize a change within that directory), and the test fails with: 
```
FAIL src/App.test.tsx
web:test:   ● Test suite failed to run
web:test:
web:test:     Cannot find module 'ui' from 'src/App.tsx'
web:test:
web:test:     Require stack:
web:test:       src/App.tsx
web:test:       src/App.test.tsx
web:test:
web:test:       1 | import React from "react";
web:test:     > 2 | import { Link } from "ui";
web:test:         | ^
web:test:       3 | import "./App.css";
web:test:       4 |
web:test:       5 | function App(): JSX.Element {
web:test:
web:test:       at Resolver.resolveModule (../../node_modules/jest-resolve/build/resolver.js:324:11)
web:test:       at Object.<anonymous> (src/App.tsx:2:1)
web:test:       at Object.<anonymous> (src/App.test.tsx:3:1)
```

### Expected Behavior

The test should pass and be able to properly resolve the `ui` directory.

### To Reproduce

Run `npx create-turbo@latest -e with-create-react-app`, make a change within App.tsx (just a copy change), and see that the test fails.

**Comment by Zertsov** [comment]
This sounds like it might be because the `types` in the `packages/ui/package.json` are dependent on a `dist` folder. If you run a `turbo build`, does the issue still happen?

**Comment by anthonyshew** [comment]
@kateEcobb This example wasn't getting the love that it needed since `create-react-app` itself is deprecated. As timing would have it, we deprecated our example over the weekend to free up some focus for the rest of our examples.

@Zertsov is correct in that this was/is a type-level issue. If you'd like to see how to run TypeScript types correctly through your workspace/packages, we've freshly updated all the other examples in our repo with the latest recommended settings from the TypeScript team.
