### ISSUE TITLE
with-docker example is not working

### ISSUE THREAD

**Issue by Rusinas** [vercel/turbo#6841]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://github.com/vercel/turbo/tree/main/examples/with-docker

### What package manager are you using / does the bug impact?

Yarn v2/v3 (node_modules linker only)

### What operating system are you using?

Windows

### Which canary version will you have in your reproduction?

latest

### Describe the Bug

So, I am trying to build a Docker image from the example repo, but I get this error:

```
ERROR: failed to solve: failed to compute cache key: failed to calculate checksum of ref 09c46b02-507c-4ba7-8483-41ea943016ff::s2e4q83c7xpc23aedk46o5e78: "/turbo.json": not found
```
If I comment `COPY turbo.json turbo.json`, I will get another error:
```
 > [builder 6/6] RUN turbo prune web --docker:
0.283 Turbo error: could not resolve workspaces: We did not find a package manager specified in your root package.json. Please set the "packageManager" property in your root package.json (https://nodejs.org/api/packages.html#packagemanager) or run `npx @turbo/codemod add-package-manager` in the root of your monorepo.
```

In the [docs](https://turbo.build/repo/docs/handbook/deploying-with-docker) the example Dockerfile is a bit different, there is no `COPY turbo.json turbo.json`, but the second error is the same. How can I fix that? Did I do something wrong?

### Expected Behavior

Build docker image successfully

### To Reproduce

Run docker build -t turbo-with-docker .

**Comment by anthonyshew** [comment]
I just tried building the `web` app using the command in the README and it was successful straightaway:
```
docker build -f apps/web/Dockerfile . --build-arg TURBO_TEAM=“your-team-name” --build-arg TURBO_TOKEN=“your-token“ --no-cache
```

Note that Docker will need you to run the command from the root of your monorepo so that all of the required files will be in context. This is a Docker requirement. (This may not be what you're running into but I mention it because it's something I've seen before helping out other folks when they were seeing files be missing.)

I'm also seeing that you're using yarn v2/v3 so the Dockerfile might need some massaging to accompany the new yarn version. Your error doesn't seem to be related to package manager versions but I'm not a yarn expert so not sure! Can you confirm that it works with yarn v1?

**Comment by anthonyshew** [comment]
> Note that Docker will need you to run the command from the root of your monorepo so that all of the required files will be in context. This is a Docker requirement.

For what it's worth, one could also run the Docker commands from a sub-directory and path up to the root context.

**Comment by anthonyshew** [comment]
Will close this for inactivity!
