### ISSUE TITLE
"No previous deployments found" for `turbo-ignore` when on a new branch

### ISSUE THREAD

**Issue by bitttttten** [vercel/turbo#7350]
### Verify canary release

- [X] I verified that the issue exists in the latest Turborepo canary release.

### Link to code that reproduces this issue

https://gist.github.com/bitttttten/39ae5caf3c105abb879ee65d77e24285

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

### Which canary version will you have in your reproduction?

turbo-ignore@1.12.3

### Describe the Bug

When checking out a new branch, we see that turbo-ignore doesn't pick up the last commit on the branch we came off from.

In the Vercel Ignore Build step:

```sh

15:18:01.643 | Running build in Washington, D.C., USA (East) – iad1
-- | --
15:18:01.769 | Cloning my-monorepo (Branch: branched-off-staging, Commit: 2bf0ac3)
15:18:04.714 | Cloning completed: 2.945s
15:18:04.714 | Running "npx turbo-ignore"
15:18:06.127 | npm WARN exec The following package was not found and will be installed: turbo-ignore@1.12.3
15:18:06.419 | ≫   Using Turborepo to determine if this project is affected by the commit...
15:18:06.420 |  
15:18:06.423 | ≫   Inferred "web" as workspace from "package.json"
15:18:06.423 | ≫   Using "build" as the task from the arguments
15:18:06.423 | ≫   No previous deployments found for "web" on branch "branched-off-staging"
15:18:06.424 | ✓ Proceeding with deployment
```

Even thought it is possible to go look at the staging branch and see that there is a deployment for "web" in this monorepo.

Locally I can also reproduce:

```sh
git checkout staging; git checkout -b test; npx turbo-ignore
```

Gives me:

```sh
Switched to a new branch 'test'
≫   Using Turborepo to determine if this project is affected by the commit...

≫   Inferred "web" as workspace from "package.json"
≫   Using "build" as the task from the arguments
≫   Analyzing results of `dotenv -- turbo --preflight "build" --filter="web...[HEAD^]" --dry=json`
≫   This commit affects "web"
✓ Proceeding with deployment
```

Which should also say that there is a preview deploy already.. right?

### Expected Behavior

turbo-ignore looks to the branch we branched off from to check for deployments.

### To Reproduce

```sh
cd apps/web; git checkout staging; git checkout -b test; npx turbo-ignore
```

### Additional context

I would understand if vercel wants to rebuild the app since it uses new VERCEL_GIT_COMMIT_REF, although locally I would imagine that turbo-repo knows that there is a previous build on staging.

**Comment by tknickman** [comment]
Hey @bitttttten, this is a limitation on Vercel due to the way the repo is cloned (to keep clones speeds, we only get details about the current branch, no others) so Vercel doesn't know about your base to compare against.

There are more details about this here: https://github.com/vercel/turbo/issues/6310#issuecomment-1787281389

But stay tuned, we're working on a better way to do this on the Vercel side!

If you're not using this on Vercel, you can provide another comparison to use via `--fallback=<...>`. For example:

`npx turbo-ignore --falback=staging` will compare the HEAD of your current branch to the HEAD of the `staging` branch.


I'm going to close this one since we already have https://github.com/vercel/turbo/issues/6310 to track here.
