### ISSUE TITLE
Docs: Dependency Confusion Attack

### ISSUE THREAD

**Issue by chancemartin-equipifi** [vercel/turbo#8179]
### What is the improvement or update you wish to see?

My team is trying to figure out if our internal packages could suffer from a Dependency Confusion attack. I haven't been able to find any documentation on the issue and was wondering if you could add some

### Is there any context that might help us understand?

How can I be sure my app is using my internal package versus one published to a remote registry with the same name?

**Comment by anthonyshew** [comment]
This is a question about package managers and how they handle dependency installation. You'll have better luck asking in the community for your package manager.

In short, this is particularly an issue with npm and yarn, since they use the `"*"` moniker to refer to internal packages. pnpm uses `"workspace:*"` to mitigate this.

Another strategy you can use is to namespace your internal packages, like `@repo/ui`.

Again, this isn't a Turborepo concern, so it's likely we won't be documenting it.
