### ISSUE TITLE
Cache affected by incremental builds

### ISSUE THREAD

**Issue by Kilcekru** [vercel/turbo#839]
### What version of Turborepo are you using?

1.1.2

### What package manager are you using / does the bug impact?

pnpm

### What operating system are you using?

Linux

### Describe the Bug

I use turborepo together with typescript incremental builds.
If turborepo has a cache miss, i still profit from the faster incremental builds of typescript.

I noticed strange build results and after investigating i found out that Turborepo doesn't copy from the cache on cache hit, but instead uses hard links. Because of this a typescript build (which has not cleaned the output) will change not only the build output but also the hard linked cache entry.

On a subsequent build a cache hit might produce a wrong result, because the cache has been changed by this.

I noticed this also applies to the `.turbo` folder (which is also not cleaned in my case).
A subsequent build will override `.turbo/turbo-build.log` which makes it even harder to find the problem, because turborepo doesn not log which hash was used for a package but only replays the `turbo-build.log`, which now contains a wrong hash .

### Expected Behavior

Cache is not affected by changing files inside a package output folder.

I understand the reasoning for hard links, but the speed gain of hard links over copying files is much smaller than incremental builds.
There should be a configuration flag to disable hard-linking and use copying instead.
It also would be nice, if the documentation would mention that cache entries are hard linked instead of copied.

### To Reproduce

Use turborepo together with typescript incremental builds inside a mono repo.
Not cleaning output of packages before rebuilding leads to the described problem.

**Comment by arthur-caillaud** [comment]
We are seeing similar issues in our monorepo.

**Comment by dobesv** [comment]
Is the issue that typescript is writing to the existing file instead of replacing it?

Are the js files the issue, or tsbuildinfo?

Do you think it's possible to find a specific sequence of steps that reproduces a build issue caused by this?

**Comment by dmnd** [comment]
I noticed that the turborepo docs [now state][1] the "simplest configuration for a Next.js application" excludes the nextjs cache directory, which is where these `*.tsbuildinfo` files end up in a Next.js application. So I wonder if the issues described above can be avoided by ensuring these files are not part of the output for a task, which should ensure they are not cached.

I'm changing my config to the following and hopefully I never end up grumbing at this issue again...:

```json
"build": {
  "outputs": [
    ".next/**", "!.next/cache/**",
    "dist/**", "!dist/*.tsbuildinfo"
  ]
}
```

[1]: https://turbo.build/repo/docs/core-concepts/caching/what-to-cache#exclusions

**Comment by Zertsov** [comment]
After team discussion, we're going to close this due to the old age of the `turbo` version mentioned in the issue. If you see that this is still happening in `turbo` v1.10+, please re-open.

**Comment by JCMais** [comment]
is anyone using typescript with incremental builds + turborepo? How does you config looks like?

**Comment by david-wasser** [comment]
I don't have a repro (or permission to reopen this issue), but I think `tsc` incremental builds as they're implemented today are incompatible with `turbo` caching. Additionally, I've observed inconsistent typechecking failures on `turbo` release 2.6.3 that are resolved after deleting `*.tsbuildinfo` files, but do not have a consistent repro. I'll try to capture more data the next time I observe this

I say they're incompatible because https://github.com/microsoft/TypeScript/issues/32023#issuecomment-2044124979 calls out that incremental builds work by tracking the file timestamp on the most recently modified file. In the case of cache hits in `turbo` though, `turbo` will often update timestamps on many output files without invoking `tsc` and should hit the same potential incorrectness issues as described in the comment. Also, the linked TypeScript issue also calls out that `*.tsbuildinfo` files are not portable between machines, so they would be incompatible in a `turbo` remote cache. The result of these issues is that incremental mode should risk being incorrect (at least with a remote cache) whether or not you're specifying your `*.tsbuildinfo` as a task output.
