### ISSUE TITLE
Syntax error while running turbo in docker container

### ISSUE THREAD

**Issue by pavlohibey** [vercel/turbo#980]
### What version of Turborepo are you using?

1.1.10

### What package manager are you using / does the bug impact?

npm

### What operating system are you using?

Mac

#### Issue statement
While running `docker-compose up --build` on `CMD` step from Dockerfile it throws such error:
```
/app/node_modules/.bin/turbo: line 11: syntax error: unexpected word (expecting ")")
```

Locally all operations with `turbo` CLI are operating as expected.
OS: macOS Monterey 12.1, M1 Pro chip

#### Files
Dockerfile:
```dockerfile
FROM node:16-alpine

WORKDIR /app

COPY . .

RUN npm i

CMD ["npx", "turbo", "run", "dev", "--", "--scope=api", "--include-dependencies"]
```

docker-compose.yml
```docker-compose
version: "3.9"
services:
  api:
    build:
      context: ../../
      dockerfile: apps/api/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./apps/api:/app/apps/api
      - ./packages:/app/packages
```

.dockerignore
```
**/.turbo
**/node_modules
**/.git*
**/*.md
```

### Expected Behavior

`turbo` CLI is executing the given command.

### To Reproduce

1. Checkout `kitchen-sink` example locally
2. Create `Dockerfile`, `.dockerignore`, and `docker-compose.yml` in `apps/api` folder
3. Copy contents of files listed above into appropriate files you've just created
4. Run `docker-compose up --build` from `apps/api` directory

**Comment by xiechao06** [comment]
hello, I met the very same problem, I guess it's because turborepo's binary executable is different on mac (your host) and linux(docker alpine), so you should avoid overriding the docker's node_modules with your host's node_modules.
You could try https://stackoverflow.com/a/37898591/2687929, it works for me, hopes it solves your problem

**Comment by gsoltis** [comment]
@pavlohibey Can you check what `turbo` packages are installed in your docker container under `node_modules/turbo-*`? That should show you the platform that `turbo` thinks it was installed for. For instance, on my M1 macbook, I see `turbo` and `turbo-darwin-arm64`.

**Comment by ridafkih** [comment]
Getting something similar myself on an M1 Pro MBP. 

```
api                     | /home/node/node_modules/.bin/turbo: line 1: ����
                                                                          X: not found
api                     | /home/node/node_modules/.bin/turbo: line 2: syntax error: unexpected "("
api                     |  ELIFECYCLE  Command failed with exit code 2.
api                     |  ELIFECYCLE  Command failed with exit code 1.
api exited with code 1
```

**Comment by chris-olszewski** [comment]
Hi @ridafkih could you open new issue with some more information such as:
 - How you installed `turbo` / version
 - What command you're running
 - Output of `ls node_modules/turbo*` when run from your repo root

If you can provide a repo containing a reproduction that would go a long way in helping us.

I'm locking conversation to encourage new issues since errors like these require specific information to debug. For anyone who runs into this issue in the future please open a new issue.
